### ISSUE TITLE
[Bug]: End of program timestamp incorrect for referral programs via graphQL

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#9530] opened 2023-09-22 12:43 UTC
### Problem encountered

The end of program timestamp value in incorrect when retrieved via API.

This could be an issue with the datanode and confusion between UNIX time in seconds and nanoseconds

The proposal event to update referral program:

`{"id":"3638-5","block":"48DEA78622CB5BBE7C6AECE2B724A0CCDD384FAE03A5D8BA23813670EC9D01E7","type":"BUS_EVENT_TYPE_PROPOSAL","proposal":{"id":"3802ef257c7439f2a4143ded260fff5dc480ce9737dc26f55feab223a2fdd8f9","reference":"CD21FCAFD6","partyId":"cbc0f9db5ab52ac62f4cfb6ee67e802204bf94d9bd430525bddd9a3ad1f06619","state":"STATE_ENACTED","timestamp":"1695384595080919000","terms":{"closingTimestamp":"1695384600","enactmentTimestamp":"1695384601","updateReferralProgram":{"changes":{"benefitTiers":[{"minimumRunningNotionalTakerVolume":"10000","minimumEpochs":"1","referralRewardFactor":"0.001","referralDiscountFactor":"0.001"},{"minimumRunningNotionalTakerVolume":"20000","minimumEpochs":"7","referralRewardFactor":"0.005","referralDiscountFactor":"0.005"},{"minimumRunningNotionalTakerVolume":"30000","minimumEpochs":"31","referralRewardFactor":"0.01","referralDiscountFactor":"0.01"}],"endOfProgramTimestamp":"1695384611","windowLength":"5","stakingTiers":[{"minimumStakedTokens":"100","referralRewardMultiplier":"1"},{"minimumStakedTokens":"1000","referralRewardMultiplier":"2"},{"minimumStakedTokens":"1000","referralRewardMultiplier":"2"}]}}},"rationale":{"description":"Proposal to update the referral program","title":"Update Referral Program"},"requiredParticipation":"0.00000015","requiredMajority":"0.66"},"version":1,"chainId":"testnet-001","txHash":"48DEA78622CB5BBE7C6AECE2B724A0CCDD384FAE03A5D8BA23813670EC9D01E7"}`

Retrieved via gRPC:

`INFO:root:Curr referral program {'currentReferralProgram': {'version': '6', 'id': '3802ef257c7439f2a4143ded260fff5dc480ce9737dc26f55feab223a2fdd8f9', 'benefitTiers': [{'minimumRunningNotionalTakerVolume': '10000', 'minimumEpochs': '1', 'referralRewardFactor': '0.001', 'referralDiscountFactor': '0.001'}, {'minimumRunningNotionalTakerVolume': '20000', 'minimumEpochs': '7', 'referralRewardFactor': '0.005', 'referralDiscountFactor': '0.005'}, {'minimumRunningNotionalTakerVolume': '30000', 'minimumEpochs': '31', 'referralRewardFactor': '0.01', 'referralDiscountFactor': '0.01'}], 'endOfProgramTimestamp': '1695384611', 'windowLength': '5', 'stakingTiers': [{'minimumStakedTokens': '100', 'referralRewardMultiplier': '1'}, {'minimumStakedTokens': '1000', 'referralRewardMultiplier': '2'}, {'minimumStakedTokens': '1000', 'referralRewardMultiplier': '2'}], 'endedAt': '1695384611111813000'}}`

Retrieved via graphQL

```
query ReferralProgram {
  currentReferralProgram {
    id
    version
    benefitTiers {
      minimumEpochs
      minimumRunningNotionalTakerVolume
      referralDiscountFactor
      referralRewardFactor
    }
    endOfProgramTimestamp
    windowLength
    stakingTiers {
      minimumStakedTokens
      referralRewardMultiplier
    }
    endedAt
  }
}
```

```
{
  "data": {
    "currentReferralProgram": {
      "id": "3802ef257c7439f2a4143ded260fff5dc480ce9737dc26f55feab223a2fdd8f9",
      "version": 6,
      "benefitTiers": [
        {
          "minimumEpochs": 1,
          "minimumRunningNotionalTakerVolume": "10000",
          "referralDiscountFactor": "0.001",
          "referralRewardFactor": "0.001"
        },
        {
          "minimumEpochs": 7,
          "minimumRunningNotionalTakerVolume": "20000",
          "referralDiscountFactor": "0.005",
          "referralRewardFactor": "0.005"
        },
        {
          "minimumEpochs": 31,
          "minimumRunningNotionalTakerVolume": "30000",
          "referralDiscountFactor": "0.01",
          "referralRewardFactor": "0.01"
        }
      ],
      "endOfProgramTimestamp": "1970-01-01T00:00:01.695384611Z",
      "windowLength": 5,
      "stakingTiers": [
        {
          "minimumStakedTokens": "100",
          "referralRewardMultiplier": "1"
        },
        {
          "minimumStakedTokens": "1000",
          "referralRewardMultiplier": "2"
        },
        {
          "minimumStakedTokens": "1000",
          "referralRewardMultiplier": "2"
        }
      ],
      "endedAt": "2023-09-22T12:10:11.111813Z"
    }
  }
}
```

### Observed behaviour

As above

### Expected behaviour

Correct timestamp  for end of program 

### Steps to reproduce

```bash
Run the below test locally and then execute the above graphQL query locally

System Test Name - test_create_new_referral_program
System Test Branch - feat_referral_program
```

### Software version

vega - develop

### Failing test

No failing test

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/13575/

### Relevant log output

```shell
Al events are here

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/13575/artifact/test_logs/tests.teams.test_team_administration/test_create_new_referral_program/
```

**Comment by guoguojin** [comment] 2023-09-22 15:44
This is not a bug, the proto definition for the end time of the referral program is expressed as Unix time rather than Unix nano. We carry this forward and also express the timestamp as Unix time rather than Unix nano.

I'm going to close this for now, but we can have GQL return the time as Unix nano regardless of how it's expressed in the protos if necessary so feel free to re-open this again if necessary.

**Closed by guoguojin** 2023-09-22 15:44 UTC
Labels: bug, high, referral

**Comment by guoguojin** [comment] 2023-09-25 09:42
Re-opening as there is an edge case where it's possible for the referral program does start and end in the same block/epoch and DN should handle it. Also didn't notice earlier, but it looks like the GQL resolver does not resolve the timestamp correctly as it's expected the data in nanos.
