### ISSUE TITLE
Issue with migration script causing data node to stop

### ISSUE THREAD

**Issue by peterbarrow** [vegaprotocol/vega#9843] opened 2023-10-19 09:37 UTC
Running a full archival data node using network history results in the following error during the initialisation phase
```
2023-10-19T06:52:08.954+0100    INFO    datanode.start.persistentPre    start/node_pre.go:166   Enabling SQL stores
2023-10-19T06:52:09.127+0100    DEBUG   datanode.start.persistentPre.connection-source  sqlstore/market_data.go:135     Retrieving markets data from Postgres
scany: query multiple result rows: ERROR: column "product_data" does not exist (SQLSTATE 42703)
```

The postgres log gives more information about the failed query
```
postgresql-2023-10-19_000000.log:2023-10-19 05:52:09.130 UTC [32767] ERROR:  column "product_data" does not exist at character 670
postgresql-2023-10-19_000000.log-2023-10-19 05:52:09.130 UTC [32767] STATEMENT:  select synthetic_time, tx_hash, vega_time, seq_num,
postgresql-2023-10-19_000000.log-                               market, mark_price, best_bid_price, best_bid_volume,
postgresql-2023-10-19_000000.log-                               best_offer_price, best_offer_volume, best_static_bid_price, best_static_bid_volume,
postgresql-2023-10-19_000000.log-                               best_static_offer_price, best_static_offer_volume, mid_price, static_mid_price,
postgresql-2023-10-19_000000.log-                               open_interest, auction_end, auction_start, indicative_price, indicative_volume,
postgresql-2023-10-19_000000.log-                               market_trading_mode, auction_trigger, extension_trigger, target_stake,
postgresql-2023-10-19_000000.log-                               supplied_stake, price_monitoring_bounds, market_value_proxy, liquidity_provider_fee_shares,
postgresql-2023-10-19_000000.log-                               market_state, next_mark_to_market, coalesce(market_growth, 0) as market_growth,
postgresql-2023-10-19_000000.log:                               coalesce(last_traded_price, 0) as last_traded_price, product_data, liquidity_provider_sla from current_market_data
```

This looks to be an issue with the rollback not matching the fields of the new table
```
I think there might be a bug in the migration scripts. In 0028, we add the product_data column and the rollback removes that column. In 0039, we add liquidity_provider_sla column to the market_data tables, but the rollback removes the product_data , I think some bad copy paste has happened here that we didn't pick up on. [@Karel Moravec](https://vegaprotocol.slack.com/team/U027SE8U94Y) did you mean to drop the product_data column or liquidity_provider_sla?
```

**Comment by guoguojin** [comment] 2023-10-20 10:30
Closing this as the bug was not caused by the migration script, but using an incompatible binary against mainnet. The code in the binary was expecting a database that was at a higher version than the database version after it had been restarted from network history.

**Closed** 2023-10-20 14:25 UTC
Labels: datanode, schema change
