### ISSUE TITLE
Investigate how we can handle more console user clients on a data-node

### ISSUE THREAD

**Issue by peterbarrow** [vegaprotocol/vega#6441] opened 2022-10-07 10:07 UTC
As the Vega network gets more popular, we expect more people to connect console front ends to the data-nodes. This will increase the requirements on the data-nodes to support more concurrent users. We need to investigate a way to reduce the impact of each extra client to a data-node to help us scale better.

Areas to investigate include:
1. Which APIs/subscriptions use the most data?
2. How to reduce the amount of data sent to each client?
3. How to reuse subscription data for multiple clients?
4. Does compression help reduce the bandwidth impact of a large amounts of users?
5. How can the front end decide which data-nodes are best to connect to in terms of free resources?

**Comment by gordsport** [comment] 2022-12-30 12:05
closing as a duplicate of:
- https://github.com/vegaprotocol/vega/issues/5726

**Closed by gordsport** 2022-12-30 12:05 UTC
Labels: performance, DatanodeV2
