### ISSUE TITLE
[Bug]: Incorrect validation of governance initiated transfer

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#9185] opened 2023-08-24 11:58 UTC
### Problem encountered

The JSON mapping of `sourceType` to `source_type` in the proto looks to be wrong. I can't submit a proposal with a source type, as it's an `unknown field`. I can't submit a propsal without one, because it's required

### Observed behaviour

```shell
./vegawallet transaction send --level debug --wallet edd --pubkey d3adb33f --network fairground '{
     "proposalSubmission": {
       "rationale": {
         "title": "Add Lorem Ipsum market",
         "description": "An example proposal to add Lorem Ipsum market"
       },
       "terms": {
         "newTransfer": {
           "changes": {
             "amount": "10",
             "asset": "8b52d4a3a4b0ffe733cddbc2b67be273816cfeb6ca4c8b339bac03ffba08e4e4",
             "destinationType": "ACCOUNT_TYPE_GLOBAL_REWARD",
             "fractionOfBalance": "0.5",
             "oneOff": { "deliverOn": "0" },
             "transferType": "GOVERNANCE_TRANSFER_TYPE_ALL_OR_NOTHING"
           }
         },
         "closingTimestamp": 1673527276,
         "enactmentTimestamp": 1673613676
       }
     }
   }'
```

```shell
✖  ./vegawallet transaction send --level debug --wallet edd--pubkey d3adb33f --network fairground '{
     "proposalSubmission": {
       "rationale": {
         "title": "Add Lorem Ipsum market",
         "description": "An example proposal to add Lorem Ipsum market"
       },
       "terms": {
         "newTransfer": {
           "changes": {
             "amount": "10",
             "asset": "8b52d4a3a4b0ffe733cddbc2b67be273816cfeb6ca4c8b339bac03ffba08e4e4",
             "sourceType:": "ACCOUNT_TYPE_GLOBAL_REWARD",
             "destinationType": "ACCOUNT_TYPE_GLOBAL_REWARD",
             "fractionOfBalance": "0.5",
             "oneOff": { "deliverOn": "0" },
             "transferType": "GOVERNANCE_TRANSFER_TYPE_ALL_OR_NOTHING"
           }
         },
         "closingTimestamp": 1673527276,
         "enactmentTimestamp": 1673613676
       }
     }
   }'
```

> ✗ Error: the transaction does not use a valid Vega command: unknown field "sourceType:" in vega.NewTransferConfiguration

```shell
✖  ./vegawallet transaction send --level debug --wallet edd--pubkey d3adb33f --network fairground '{
     "proposalSubmission": {
       "rationale": {
         "title": "Add Lorem Ipsum market",
         "description": "An example proposal to add Lorem Ipsum market"
       },
       "terms": {
         "newTransfer": {
           "changes": {
             "amount": "10",
             "asset": "8b52d4a3a4b0ffe733cddbc2b67be273816cfeb6ca4c8b339bac03ffba08e4e4",
             "source_type:": "ACCOUNT_TYPE_GLOBAL_REWARD",
             "destinationType": "ACCOUNT_TYPE_GLOBAL_REWARD",
             "fractionOfBalance": "0.5",
             "oneOff": { "deliverOn": "0" },
             "transferType": "GOVERNANCE_TRANSFER_TYPE_ALL_OR_NOTHING"
           }
         },
         "closingTimestamp": 1673527276,
         "enactmentTimestamp": 1673613676
       }
     }
   }'
```
> ✗ Error: the transaction does not use a valid Vega command: unknown field "source_type:" in vega.NewTransferConfiguration

### Expected behaviour

I can submit a governance transfer

### Steps to reproduce

```bash
1. Use the payloads above
```

### Software version

v0.72.10 / `26afd41a2fe4cb20f3fffeae0d4cfe523fc35614` (osx arm64)

**Comment by gordsport** [comment] 2023-09-13 10:23
closing based on the above comment as not a bug

**Closed by gordsport** 2023-09-13 10:23 UTC
Labels: bug, governance, transfers
