### ISSUE TITLE
Dehistory: Data mismatches between source and restored datanode

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7139] opened 2022-12-13 16:10 UTC
**Scenario:** 
Create a network with one data node and perform a variety of transactions and then create another datanode from the latest history segment. Run the frontend graphql queries against both the datanodes and compare the results.

**Jenkins Run:**
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/35261/

**Jenkins Full Test Logs:**
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/35261/consoleText

In the above search for the below text and all the mismatches will be displayed.
**Data Mismatch **

System test branch - **feat_dehistory_tests_5**
Core vega branch - **remove-constraints-on-table-truncate**

The below errors happen when there are a lot of transactions on the system and is difficult to pip point which transaction is causing the issue.

The error message logs are loo big, hence attaching the same.

[Dehistory-Datanode-Mismatches.txt](https://github.com/vegaprotocol/vega/files/10219873/Dehistory-Datanode-Mismatches.txt)

**Comment by guoguojin** [comment] 2022-12-14 13:37
This is a duplicate of #6903 with more up-to-date information.

**Closed** 2022-12-14 13:42 UTC
Labels: critical, bug, duplicate, dehistory
