### ISSUE TITLE
[Bug]: Error in null blockchain caused by incorrect nil interface check

### ISSUE THREAD

**Issue by ettec** [vegaprotocol/vega#9348] opened 2023-09-11 10:55 UTC
### Problem encountered

When running with null blockchain the node is considered a validator but does not have a valid eth client, the check in the engine fails to catch this due to the classic Go nil interface that passes nil check has a nil value 'feature' of golang.

### Observed behaviour

"

### Expected behaviour

"

### Steps to reproduce

```bash
"
```

### Software version

develop

**Comment by gordsport** [comment] 2023-09-11 10:58
@ettec - is this a duplicate of: https://github.com/vegaprotocol/vega/issues/9334

**Closed** 2023-09-11 10:58 UTC
Labels: bug
