### ISSUE TITLE
Oracle specs are decativated after network restart from checkpoint

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8205] opened 2023-04-24 09:31 UTC
Before a network restart we have a data source spec active
Then we restart the network using a checkpoint

Oracle spec events are produced which show the oracle specs deactivated...
Expecting the existing oracle specs to be restarted as Active
This does not seem to impact the ability to terminate or settle after restart.

```
{"id":"521-5","block":"01E27B326BFEC9361528F43E43B2966A55D126DBDE9B07CE023B2CE74926E163","type":"BUS_EVENT_TYPE_ORACLE_SPEC","oracleSpec":{"externalDataSourceSpec":{"spec":{"id":"6f332bddf1b3e013ac5bf7df726a9dac521e3fdec8e4f04fe9bb7a665b8d3d7c","createdAt":"1682326952649685000","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"8d1ffa7ade9226cd70fe984af6f6c5bef7925757a5b0f73e663c8be4a9db306a"}}],"filters":[{"key":{"name":"oracle.test.termination0EA6E","type":"TYPE_BOOLEAN"},"conditions":[{"operator":"OPERATOR_EQUALS","value":"True"}]}]}}},"status":"STATUS_ACTIVE"}}},"version":1,"chainId":"testnet-003","txHash":"425F54A2023546DD5F32015C88591C5900A9FB95B2B9246963EC1D057546D130"}
stream closed err=rpc error: code = Unavailable desc = error reading from server: EOF
***NETWORK RESTART***
{"id":"40-5","block":"657D3B831D095D23B8A58C9008C72EEDCD09BDED473E972E49AD3AADE7BD8E25","type":"BUS_EVENT_TYPE_ORACLE_SPEC","oracleSpec":{"externalDataSourceSpec":{"spec":{"id":"6f332bddf1b3e013ac5bf7df726a9dac521e3fdec8e4f04fe9bb7a665b8d3d7c","createdAt":"1682325131192810000","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"8d1ffa7ade9226cd70fe984af6f6c5bef7925757a5b0f73e663c8be4a9db306a"}}],"filters":[{"key":{"name":"oracle.test.termination0EA6E","type":"TYPE_BOOLEAN"},"conditions":[{"operator":"OPERATOR_EQUALS","value":"True"}]}]}}},"status":"STATUS_DEACTIVATED"}}},"version":1,"chainId":"testnet-004","txHash":"85DEB3A998569B7A0B6C7528197AD8B1B3AEEEC627EB9DDEF3F1C28AD7A466CE"}
{"id":"41-14","block":"A44188278C603DFB7041F335E4CABC43995D6CC413EE0B8911956C81F87C9792","type":"BUS_EVENT_TYPE_ORACLE_SPEC","oracleSpec":{"externalDataSourceSpec":{"spec":{"id":"4dd319749baf255269430a28013b7d91e65d6674cfc68f21f7be24cf94f2d804","createdAt":"1682325131192810000","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"8d1ffa7ade9226cd70fe984af6f6c5bef7925757a5b0f73e663c8be4a9db306a"}}],"filters":[{"key":{"name":"oracle.test.settlement0750A","type":"TYPE_INTEGER"},"conditions":[{"operator":"OPERATOR_GREATER_THAN_OR_EQUAL","value":"0"}]}]}}},"status":"STATUS_DEACTIVATED"}}},"version":1,"chainId":"testnet-004","txHash":"30B0662A882C7219967A84C8E8C93B0934B79121504884499C6DA85202B8C13C"}

```

jenkins https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/68036/

**Comment by vega-paul** [comment] 2023-04-25 09:45
test ID
test_can_terminate_and_settle_after_checkpoint

**Comment by AnExsomnis** [comment] 2023-04-25 10:59
Closing this because it cannot be reproduced anymore post restart.

**Closed by AnExsomnis** 2023-04-25 10:59 UTC
Labels: oracles, bug
