### ISSUE TITLE
Revoke permissions 

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/vega#7721] opened 2023-03-01 11:53 UTC
# Problem encountered

Revoking permissions keeps the host name in the list of permissions, not sure if this is intended.

# Observed behaviour

Can't seem to get rid of a host permissions once I allowed the host to have read access. For more info, see the steps to reproduce. Not sure if this is by design, currently have a workaround in the frontend to be able to hide the non-relevant hostnames.

# Expected behaviour

I can't see any reason to keep the hostname in the list once the permissions for it got revoked, but maybe i'm missing something. The list can grow very long over time, cause nothing ever gets removed.
Because of this I needed to implement a hack on the frontend to hide permission entries which have both `access: none` and the host is not actively connected to the wallet.

# Steps to reproduce

## Manual

1. create a connection with `client.connect_wallet`
2. get the list of permissions with `admin.list_permissions`
3. revoke the permissions for the host with `admin.revoke_permissions`
4. when you list the permissions again, the hostname will be in the list with access: "none"

**Comment by wwestgarth** [comment] 2023-03-01 16:13
Can't reproduce this problem in the backend. If I start with hostname with permissions, revoke, then list then it is removed from the list. If I then _describe_ the permissions for that host it'll return `none`. This is by design and is the returned response for any hostname even if it never had permissions at any point.

```
$ vega wallet permissions list --wallet=permtest --output=json
{"permissions":{"some-hostname":{"public_keys":"read"}}}

$ vega wallet permissions revoke --wallet=permtest --hostname=some-hostname --output=json

$ vega wallet permissions list --wallet=permtest --output=json
{"permissions":{}}

$ vega wallet permissions describe --wallet=permtest --output=json --hostname=some-hostname
{"permissions":{"publicKeys":{"access":"none","allowedKeys":null}}}
```

So I suspect its the frontend holding on to the hostname with revoked permissions and untentionally calling `describe` on it?

**Comment by gordsport** [comment] 2023-03-01 23:11
@notbot00 

based on the above comment please can you either add further details or close as wont fix.

**Closed** 2023-03-06 10:22 UTC
Labels: wallet, bug, to-confirm, not-a-bug
