### ISSUE TITLE
Staging 1 panic: received event MarginLevelsEvent between end block and begin block

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#6571] opened 2022-10-22 08:41 UTC
Full details on investigation:
https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1666427697863579

This ticket will be updated as more info known.

Log:

```
Oct 21 16:48:08 n00.stagnet1.vega.xyz visor[73353]: 
panic: received event MarginLevelsEvent between end block and begin block
goroutine 131 [running]:
code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).processBlock(0xc0001fab00, {0x2b3d288, 0xc001460cc0}, {0x2b3d330, 0xc002961e30}, 0xc0044d7dc0, 0xc00146ca20, 0xc00146ca80)
        /home/runner/work/vega/vega/datanode/broker/sqlstore_broker.go:283 +0xfa5
code.vegaprotocol.io/vega/datanode/broker.(*SQLStoreBroker).Receive(0xc0001fab00, {0x2b3d288, 0xc001460cc0})
        /home/runner/work/vega/vega/datanode/broker/sqlstore_broker.go:125 +0x165
code.vegaprotocol.io/vega/cmd/data-node/commands/start.(*NodeCommand).runNode.func5()
        /home/runner/work/vega/vega/cmd/data-node/commands/start/node.go:120 +0x34
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:75 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/runner/go/pkg/mod/golang.org/x/sync@v0.0.0-20220819030929-7fc1605a5dde/errgroup/errgroup.go:72 +0xa5
```

**Comment by ze97286** [comment] 2022-10-22 09:06
discussed in details on this thread - https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1666271359415339

**Comment by ze97286** [comment] 2022-10-22 09:26
More details: 
This is happening after the node ran out of memory and restarted by visor and the chain is being replayed. The replay is very fast (as it already has the blocks) and it gets from 1 to 52875 in less than 7 minutes. This seems to be putting datanode under significant stress as can be observed from the queue seemingly getting full:

```
Oct 21 16:44:37 n00.stagnet1.vega.xyz visor[73352]: 2022-10-21T16:44:37.063Z        ERROR        broker        broker/socket_client.go:215        Failed to queue message on socket        {"error": "send time out"}
Oct 21 16:44:40 n00.stagnet1.vega.xyz visor[73352]: 2022-10-21T16:44:40.952Z        ERROR        broker        broker/socket_client.go:215        Failed to queue message on socket        {"error": "send time out"}
Oct 21 16:44:44 n00.stagnet1.vega.xyz visor[73352]: 2022-10-21T16:44:44.980Z        ERROR        broker        broker/socket_client.go:215        Failed to queue message on socket        {"error": "send time out"}
Oct 21 16:44:48 n00.stagnet1.vega.xyz visor[73352]: 2022-10-21T16:44:48.711Z        ERROR        broker        broker/socket_client.go:215        Failed to queue message on socket        {"error": "send time out"}
Oct 21 16:44:52 n00.stagnet1.vega.xyz visor[73352]: 2022-10-21T16:44:52.227Z        ERROR        broker        broker/socket_client.go:215        Failed to queue message on socket        {"error": "send time out"}
Oct 21 16:44:55 n00.stagnet1.vega.xyz visor[73352]: 2022-10-21T16:44:55.979Z        ERROR        broker        broker/socket_client.go:215        Failed to queue message on socket        {"error": "send time out"}
Oct 21 16:44:59 n00.stagnet1.vega.xyz visor[73352]: 2022-10-21T16:44:59.166Z        ERROR        broker        broker/socket_client.go:215        Failed to queue message on socket        {"error": "send time out"}
Oct 21 16:45:02 n00.stagnet1.vega.xyz visor[73352]: 2022-10-21T16:45:02.351Z        ERROR        broker        broker/socket_client.go:215        Failed to queue message on socket        {"error": "send time out"}
Oct 21 16:45:06 n00.stagnet1.vega.xyz visor[73352]: 2022-10-21T16:45:06.835Z        ERROR        broker        broker/socket_client.go:215        Failed to queue message on socket        {"error": "send time out"}
Oct 21 16:45:11 n00.stagnet1.vega.xyz visor[73352]: 2022-10-21T16:45:11.036Z        ERROR        broker        broker/socket_client.go:215        Failed to queue message on socket        {"error": "send time out"}

```

It seems like this is somehow leading to datanode thinking events are out of order. 

[n00_between_blocks.log.zip](https://github.com/vegaprotocol/vega/files/9843976/n00_between_blocks.log.zip)

**Comment by guoguojin** [comment] 2022-10-25 13:58
I haven't been able to reproduce this, but I've been able to reproduce core going down by replaying from snapshot because the event buffer got filled. 

This PR [https://github.com/vegaprotocol/vega/pull/6581](https://github.com/vegaprotocol/vega/pull/6581) contains buffering for the data-node which should resolve the issue once it has merged. I've cherry picked the buffering from this branch and added to the v0.59.0 release and tested a restart with the buffering turned on and this stopped core from panicking. Data-node takes a while to catch up, but it does eventually without things panicking.

**Comment by gordsport** [comment] 2022-10-26 13:57
Along with linked PR this issue also requires the fix to be covered under issue:
- https://github.com/vegaprotocol/vega/issues/6601

**Comment by guoguojin** [comment] 2022-10-28 13:48
#6581 has been merged now so this should be resolved, closing for now

**Closed by guoguojin** 2022-10-28 13:48 UTC
Labels: crasher, critical, bug, DatanodeV2
