### ISSUE TITLE
Data mismatch between data in restored datanode and core

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7433] opened 2023-01-25 16:59 UTC
Recently a Jenkins pipeline change was made to create a new datanode from latest network history and compare the data against core using the database diff tool.

This has highlighted some data difference between a restored datanode and core.

**Note: This may NOT be a bug but just that we don't store the withdrawal history in restored datanodes, if that be the case then the database diff tool should be tweaked to accommodate the difference.**

See below pipeline for details:

https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/44598/pipeline/412

The difference seems to be in the withdrawals table

```
[2023-01-25T01:44:08.135Z] key=withdrawals, matchResult=mismatching number of elements, coreLength=3, datanodeLength=0, coreResult=id:"45f91e6fe0dfc3157c00aa7f5b47bea8aa2e38a4fab5401d114dfc335eb59e07" party_id:"2a4045cf371c5bde5973072386ff075280f5225b52a91be280aae70f99dbe1a4" amount:"10" asset:"ce12db3e1046e87002360849c87e2467c0695360f1c1c87f75f2a2ea45a2cfaa" status:STATUS_REJECTED ref:"1674610676" created_timestamp:1674610675973450000

[2023-01-25T01:44:08.135Z] id:"7c739e204d05320ca49705ad0c4c866f1a58a813c05d00406916a54a1d6b4bf5" party_id:"2a4045cf371c5bde5973072386ff075280f5225b52a91be280aae70f99dbe1a4" amount:"9" asset:"79e7131cb9ceb7ee87b6d8e1ab803bb6e0151f08e727d3e088aa651f311dff52" status:STATUS_REJECTED ref:"1674610575" created_timestamp:1674610575621680000

[2023-01-25T01:44:08.135Z] id:"83c086b230789127315f6bcd2597a1717b1c64b4c0243964c66073cc3720261b" party_id:"2a4045cf371c5bde5973072386ff075280f5225b52a91be280aae70f99dbe1a4" amount:"9" asset:"eb8632644196ed9b358bdd5e51f80d61b934b14020899fd70360a3e4cff467a1" status:STATUS_FINALIZED ref:"1674610757" tx_hash:"0x0e14c4338b54cf49f2b8442a5ed371ea82fc0b73b5460673935130e33298ca20" created_timestamp:1674610755179044000 withdrawn_timestamp:1674610772506645000

[2023-01-25T01:44:08.135Z] , datanodeResult=
```

**Comment by pscott31** [comment] 2023-01-26 16:41
OK so I had a good rummage around here and I think I can declare NotABug - though I did find it a bit surprising and it's slightly sub-optimal to have a difference in how core/datanode view withdrawals.

Core keeps all withdrawals ever in a map in memory and stores it in checkpoints, even once finalized on the foreign chain. I'm not 100% sure this is actually what we want as it will grow forever, but that's what it does ([slack thread](https://vegaprotocol.slack.com/archives/C9E6XA8GK/p1674747867509189)). 

Datanode counts these as history, so they aren't included as part of the 'current state' snapshot - so unless you load some history segments you won't see historical withdrawals. This seems like sensible behaviour to me.

I can tweak the diff tool to ignore withdrawals completely if you like, or is that a bit to drastic?

**Comment by MuthuVega** [comment] 2023-01-26 16:49
Thanks @pscott31 

Yes , think we need to tweak the diff tool **BUT** can we do it so that the data in the datanode is always a subset of whats in core. ( meaning the datanode could be empty OR if there is anything , then that's definitely present in core)

Not too sure how easy / difficult it is to do this , but this would be ideal for us.

**Comment by pscott31** [comment] 2023-01-26 16:51
OK sure. I've made [an issue](https://github.com/vegaprotocol/vega/issues/7440) to see if we want to change how core behaves as well.

**Comment by pscott31** [comment] 2023-01-26 18:01
I think this should do it https://github.com/vegaprotocol/vegatools/pull/259

**Comment by gordsport** [comment] 2023-01-30 13:12
Closing this issue as it will be addressed by:

short term:
- https://github.com/vegaprotocol/vegatools/issues/258

long term:

- https://github.com/vegaprotocol/vega/issues/7440

**Comment by MuthuVega** [comment] 2023-02-02 10:49
Reopening as the issue doesn't seem to be resolved 
Still can see that the command `vegatools difftool -s ./snapshot-tmp -d 127.0.0.1:3037` is complaining regarding data mismatch.

Jenkins Pipeline:
https://jenkins.ops.vega.xyz/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/46715/pipeline/412

cc: @pscott31 @gordsport

**Comment by gordsport** [comment] 2023-02-02 10:52
@MuthuVega

please retest and close if ok when the issue is resolved as per the comment above:

https://github.com/vegaprotocol/vega/issues/7433#issuecomment-1408610002

**Comment by pscott31** [comment] 2023-02-02 10:53
I haven't managed [to get my commit](https://github.com/vegaprotocol/vegatools/pull/259) into vegatools yet; the github action to attempt to build the binaries times out after 3 hours (I think don't think it's a problem with my change, but some github strangeness). I'll have another crack at it. In the mean time, feel free to try it with the `withdrawals_diff` vegatools branch

**Closed** 2023-05-23 10:47 UTC
Labels: bug, DatanodeV2, high, network-history
