### ISSUE TITLE
[Bug]: `FundingPaymentsEvent` contains theoretical, not actual funding payments per party

### ISSUE THREAD

**Issue by witgaw** [vegaprotocol/vega#10718] opened 2024-02-20 11:39 UTC
The event is generated after funding payments get calculated:
https://github.com/vegaprotocol/vega/blob/develop/core/execution/future/market.go#L4426

This doesn't take into account party's collateral at this stage resulting in theoretical funding payments which may differ from actual ones if any of the liable parties doesn't have sufficient collateral to cover the funding payment and the market's insurance pool balance is insufficient to cover the shortfall.

Displaying both the theoretical and actual amount would be ideal.

**Comment by jeremyletang** [comment] 2024-08-23 12:04
closed as duplicate of: https://github.com/vegaprotocol/vega/issues/11512

**Closed by jeremyletang** 2024-08-23 12:04 UTC
Labels: bug
