### ISSUE TITLE
[Bug]: Event-file difference identified in test run

### ISSUE THREAD

**Issue by wwestgarth** [vegaprotocol/vega#10181] opened 2023-11-29 08:27 UTC
### Problem encountered

In this Jenkins run:
https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/31353/pipeline

the soak test job failed because it detected a difference in event files produced by the data-node, this usually means some events were sent in a different order and can lead to differences in history segments. It could also be a false positive, who knows.

```
[2023-11-28T16:35:41.830Z] === Starting event-file diff

[2023-11-28T16:35:41.830Z] Differences found between: /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/vega/node2/eventlog.evt /jenkins/workspace/common/system-tests-wrapper/networkdata/testnet/vega/node2/eventlog-replay.evt
```

the files to diff can be found here:
https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/31353/artifact/testnet/vega/node2/

details on how to debug this can be found here:
https://github.com/vegaprotocol/vega/tree/develop/core/snapshot#event-diff-soak-tests

### Observed behaviour

Events sent out from core in an non-deterministic order.

### Expected behaviour

Events sent out from core in an deterministic order.

**Comment by peterbarrow** [comment] 2023-11-29 12:51
Following the instruction above I generated the JSON versions of the event files and compared them. The only difference was 3 transactions that were at the end of the original file were not present in the replayed file. This looks like the file was closed before being flushed. Checking with Jeremy he confirmed this can happen. Therefore I'm closing this ticket as it is not a problem with out-of-order events.

**Closed by peterbarrow** 2023-11-29 12:51 UTC
Labels: events, bug, network-history
