### ISSUE TITLE
error details not thrown in case of erc20 asset proposal validation error 'PROPOSAL_ERROR_NODE_VALIDATION_FAILED'

### ISSUE THREAD

**Issue by claudiumilea** [vegaprotocol/vega#6290] opened 2022-09-23 16:26 UTC
# Problem encountered
We receive error details data back in the event after a proposal rejection for network param/market or asset invalid proposals.

Error details not present on the erc20 asset proposal validation rejection in case of rejection reason 'PROPOSAL_ERROR_NODE_VALIDATION_FAILED'

# Observed behaviour
There are no error details in the event log

# Expected behaviour
An error message should also be added apart from the already existing rejection reason.

# System response
{"id":"30126-39","block":"C2E9A9CAF476845E79ACABC1275022637CD9607D975C8D8FD5B6D9F287C5BEDF","type":"BUS_EVENT_TYPE_PROPOSAL","proposal":{"id":"725d5481282e77a8988876d78d860dd85015136b024646d102568fa8a111e5ed","reference":"C167B67FDB","partyId":"09c31dfb303193ccdb9309ca5d2128086068c61cfaa30ac906307c0389c8b5ee","state":"STATE_REJECTED","timestamp":"1663949423082834000","terms":{"closingTimestamp":"1663949435","enactmentTimestamp":"1663949436","validationTimestamp":"1663949434","newAsset":{"changes":{"name":"4329493661 emaN tessA tseT","symbol":"DFB","decimals":"18","quantum":"1","erc20":{"contractAddress":"0xd30307745A04d284DCcE6A083Ac4c734ac9Dc8bB","lifetimeLimit":"100000000000000000000000000","withdrawThreshold":"1000000000000000000000"}}}},"reason":"PROPOSAL_ERROR_NODE_VALIDATION_FAILED","rationale":{"description":"New asset","title":"Asset Proposal: 4329493661 emaN tessA tseT"},"requiredParticipation":"0.00000015","requiredMajority":"0.66"},"version":1,"chainId":"test-chain-78U4rY","txHash":"C2E9A9CAF476845E79ACABC1275022637CD9607D975C8D8FD5B6D9F287C5BEDF"}

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:

## Automation
`test_asset_name = f'Test Asset Name {str(int(time.time()))}'
    test_asset_code = "".join(choices(ascii_uppercase, k=3))
    test_asset_decimals = 18

    as_withdraw_thresh = astsMod.scale_to_asset_decimal_places(amount=1000, override_asset_precision=18)
    as_life_limit = astsMod.scale_to_asset_decimal_places(amount=100000000, override_asset_precision=18)
    erc20_asset = governMod.ERC20Asset(name=test_asset_name,
                                       sym=test_asset_code,
                                       contract_address=None,
                                       withdraw_threshold=as_withdraw_thresh,
                                       lifetime_limit=as_life_limit,
                                       decimals=test_asset_decimals,
                                       )
    # Create the token in ganache
    erc20_asset.deploy_contract()
    # Override name param in asset submission.
    erc20_asset.name = test_asset_name[::-1]
    erc20_asset.sym = test_asset_code[::-1]

    # Create the proposal in vega. Vote.
    erc20_asset.propose(proposer, state="Rejected", proposal_exception_expected=True)
    assert 'PROPOSAL_ERROR_NODE_VALIDATION_FAILED' in erc20_asset.current_proposal.rejection_reason`

# Evidence

## Logs
If applicable, add logs and/or screenshots to help explain your problem.

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by wwestgarth** [comment] 2022-09-23 16:44
Duplicate of https://github.com/vegaprotocol/vega/issues/5473

**Comment by gordsport** [comment] 2022-09-24 10:42
Closing as a duplicate of a bug scheduled as 🤠🤸 - stretch task for the enable trading timeframe.

**Comment by ze97286** [comment] 2022-09-25 14:40
Closing as a duplicate of a bug scheduled as 🤠🤸 - stretch task for the enable trading timeframe.

**Closed by ze97286** 2022-09-25 14:40 UTC
Labels: Medium, assets, bug, duplicate
