### ISSUE TITLE
Panic received when starting datanode - Failed to process committed block 

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#7008] opened 2022-12-01 14:22 UTC
Running against the below branches:

vega - `dehistory-failed-to-get-analysis`
vegacapsule - `add-swarm-key-support`
systemtests - `fix_datanpode_swarmkey_config`

Jenkins Run:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/31722/

Error Received:

```
panic: Failed to process committed block (1252:2E0BB9657198C6DB60FF6662898B61845D8886DAEEEFA5637EC8A0D0C429D511): leveldb: closed

goroutine 481 [running]:
github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).poolRoutine(0xc000359a40, 0x1)
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:403 +0x12da
created by github.com/tendermint/tendermint/blockchain/v0.(*BlockchainReactor).SwitchToFastSync
	/jenkins/GOPATH/pkg/mod/github.com/tendermint/tendermint@v0.34.24/blockchain/v0/reactor.go:127 +0xe5
```

Jenkins Error Log:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/31722/artifact/testnet/logs/testnet-nodeset-full-9-full/vega-full-9.stderr-2022-12-01T13%3A44%3A11Z.log/*view*/

**Comment by wwestgarth** [comment] 2022-12-01 16:29
This looks to be a duplicate of https://github.com/vegaprotocol/vega/issues/6680 where TM has bugs where sometimes it can't shutdown gracefully, so isn't really an issue.

The reason for the shutdown is because that datanode can't start because it hasn't restored from a snapshot, but core has:
```
block height on begin block, 1249, is too high, the height of the last processed block is 0
```

which I think is the intention given the test-name `test_datanode_restore_where_core_block_greater_than_datanode_block`

So I'll mark as a duplicate of 6680.

**Closed** 2022-12-01 16:29 UTC
Labels: critical, bug, duplicate, dehistory
