### ISSUE TITLE
[Bug]: Four identical BUS_EVENT_TYPE_MARKET_UPDATED events for a proposed market

### ISSUE THREAD

**Issue by jgsbennett** [vegaprotocol/vega#8460] opened 2023-06-08 10:43 UTC
### Problem encountered

When you propose a market, vega issues four seemingly-identical events to announce that the market has been proposed, save for their transaction order in the block.

### Observed behaviour

Four seemingly identical BUS_EVENT_TYPE_MARKET_UPDATED proposed events within one block.

### Expected behaviour

One event to announce the proposal. Possibly more if there is some change of state, but even so, if it all takes place within one block I'd still hope that only one event per block would be necessary.

### Steps to reproduce

```bash
1. Run, for instance: pytest tests/assets -k test_Markets
2. Check eventscanner/BUS_EVENT_TYPE_MARKET_UPDATED.txt
```

### Software version

e6d1d56d9f46fc7851976ffe8932a7f46159e2cb

### Jenkins run

Any. But for instance: https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/73613/artifact/test_logs/tests.assets.api_test/test_Markets/BUS_EVENT_TYPE_MARKET_UPDATED.txt

### Relevant log output

```shell
{"id":"4123-26","block":"9C73D94B0B0950451E45BBFBA6E4EE6D563709BB235FF48FFF86EAC6B743A223","type":"BUS_EVENT_TYPE_MARKET_UPDATED","marketUpdated":{"id":"b0974651966033ccf885205482a7cf1af3a2450e52e6648c8e1d7bbc714c53d1","tradableInstrument":{"instrument":{"code":"CRYPTO:VEGA CORE SYS TEST","name":"Futures System-Tests Market","metadata":{"tags":["asset_class:fx/crypto","product:futures"]},"future":{"settlementAsset":"606189f865f23d5ca7429fbd3b186b1578b6e3551ab3561b08c1aace7cbc5a5b","quoteName":"USD","dataSourceSpecForSettlementData":{"id":"44f5b806f74bc593181a1704b0e7c1e5245f2176c5c85fdd7b524fbf1e8972bd","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"5aafa77b998573d6d6e1cacc776b5e743b8adfe85eaa012bd53e48791a6c8a72"}}],"filters":[{"key":{"name":"oracle.test.settlement7370C","type":"TYPE_INTEGER","numberDecimalPlaces":"3"},"conditions":[{"operator":"OPERATOR_GREATER_THAN_OR_EQUAL","value":"0"}]}]}}}},"dataSourceSpecForTradingTermination":{"id":"00795fcb5fc877355dc738e87dccfb570ef558fa1b8e017dc406791ed9759d39","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"5aafa77b998573d6d6e1cacc776b5e743b8adfe85eaa012bd53e48791a6c8a72"}}],"filters":[{"key":{"name":"vegaprotocol.builtin.timestamp","type":"TYPE_TIMESTAMP"},"conditions":[{"operator":"OPERATOR_EQUALS","value":"1686016250"}]}]}}}},"dataSourceSpecBinding":{"settlementDataProperty":"oracle.test.settlement7370C","tradingTerminationProperty":"vegaprotocol.builtin.timestamp"}}},"marginCalculator":{"scalingFactors":{"searchLevel":1.1,"initialMargin":1.2,"collateralRelease":1.4}},"logNormalRiskModel":{"riskAversionParameter":0.001,"tau":0.00011407711613050422,"params":{"r":0.016,"sigma":1.5}}},"decimalPlaces":"5","fees":{"factors":{"makerFee":"0.004","infrastructureFee":"0.001","liquidityFee":"0"}},"openingAuction":{"duration":"13"},"priceMonitoringSettings":{"parameters":{}},"liquidityMonitoringParameters":{"targetStakeParameters":{"timeWindow":"10","scalingFactor":5},"triggeringRatio":"0","auctionExtension":"1"},"tradingMode":"TRADING_MODE_NO_TRADING","state":"STATE_PROPOSED","marketTimestamps":{"proposed":"1686016209415381094","pending":"1686016209415381094","open":"1686016209415381107"},"positionDecimalPlaces":"5","lpPriceRange":"1","linearSlippageFactor":"0.01","quadraticSlippageFactor":"0"},"version":1,"chainId":"testnet-001","txHash":"B21559E0F8AED77FE094CA1067FC1E42CE4B567F9812702FCAF83A769CF21F0D"}
{"id":"4123-27","block":"9C73D94B0B0950451E45BBFBA6E4EE6D563709BB235FF48FFF86EAC6B743A223","type":"BUS_EVENT_TYPE_MARKET_UPDATED","marketUpdated":{"id":"b0974651966033ccf885205482a7cf1af3a2450e52e6648c8e1d7bbc714c53d1","tradableInstrument":{"instrument":{"code":"CRYPTO:VEGA CORE SYS TEST","name":"Futures System-Tests Market","metadata":{"tags":["asset_class:fx/crypto","product:futures"]},"future":{"settlementAsset":"606189f865f23d5ca7429fbd3b186b1578b6e3551ab3561b08c1aace7cbc5a5b","quoteName":"USD","dataSourceSpecForSettlementData":{"id":"44f5b806f74bc593181a1704b0e7c1e5245f2176c5c85fdd7b524fbf1e8972bd","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"5aafa77b998573d6d6e1cacc776b5e743b8adfe85eaa012bd53e48791a6c8a72"}}],"filters":[{"key":{"name":"oracle.test.settlement7370C","type":"TYPE_INTEGER","numberDecimalPlaces":"3"},"conditions":[{"operator":"OPERATOR_GREATER_THAN_OR_EQUAL","value":"0"}]}]}}}},"dataSourceSpecForTradingTermination":{"id":"00795fcb5fc877355dc738e87dccfb570ef558fa1b8e017dc406791ed9759d39","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"5aafa77b998573d6d6e1cacc776b5e743b8adfe85eaa012bd53e48791a6c8a72"}}],"filters":[{"key":{"name":"vegaprotocol.builtin.timestamp","type":"TYPE_TIMESTAMP"},"conditions":[{"operator":"OPERATOR_EQUALS","value":"1686016250"}]}]}}}},"dataSourceSpecBinding":{"settlementDataProperty":"oracle.test.settlement7370C","tradingTerminationProperty":"vegaprotocol.builtin.timestamp"}}},"marginCalculator":{"scalingFactors":{"searchLevel":1.1,"initialMargin":1.2,"collateralRelease":1.4}},"logNormalRiskModel":{"riskAversionParameter":0.001,"tau":0.00011407711613050422,"params":{"r":0.016,"sigma":1.5}}},"decimalPlaces":"5","fees":{"factors":{"makerFee":"0.004","infrastructureFee":"0.001","liquidityFee":"0"}},"openingAuction":{"duration":"13"},"priceMonitoringSettings":{"parameters":{}},"liquidityMonitoringParameters":{"targetStakeParameters":{"timeWindow":"10","scalingFactor":5},"triggeringRatio":"0","auctionExtension":"1"},"tradingMode":"TRADING_MODE_NO_TRADING","state":"STATE_PROPOSED","marketTimestamps":{"proposed":"1686016209415381094","pending":"1686016209415381094","open":"1686016209415381107"},"positionDecimalPlaces":"5","lpPriceRange":"1","linearSlippageFactor":"0.01","quadraticSlippageFactor":"0"},"version":1,"chainId":"testnet-001","txHash":"B21559E0F8AED77FE094CA1067FC1E42CE4B567F9812702FCAF83A769CF21F0D"}
{"id":"4123-28","block":"9C73D94B0B0950451E45BBFBA6E4EE6D563709BB235FF48FFF86EAC6B743A223","type":"BUS_EVENT_TYPE_MARKET_UPDATED","marketUpdated":{"id":"b0974651966033ccf885205482a7cf1af3a2450e52e6648c8e1d7bbc714c53d1","tradableInstrument":{"instrument":{"code":"CRYPTO:VEGA CORE SYS TEST","name":"Futures System-Tests Market","metadata":{"tags":["asset_class:fx/crypto","product:futures"]},"future":{"settlementAsset":"606189f865f23d5ca7429fbd3b186b1578b6e3551ab3561b08c1aace7cbc5a5b","quoteName":"USD","dataSourceSpecForSettlementData":{"id":"44f5b806f74bc593181a1704b0e7c1e5245f2176c5c85fdd7b524fbf1e8972bd","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"5aafa77b998573d6d6e1cacc776b5e743b8adfe85eaa012bd53e48791a6c8a72"}}],"filters":[{"key":{"name":"oracle.test.settlement7370C","type":"TYPE_INTEGER","numberDecimalPlaces":"3"},"conditions":[{"operator":"OPERATOR_GREATER_THAN_OR_EQUAL","value":"0"}]}]}}}},"dataSourceSpecForTradingTermination":{"id":"00795fcb5fc877355dc738e87dccfb570ef558fa1b8e017dc406791ed9759d39","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"5aafa77b998573d6d6e1cacc776b5e743b8adfe85eaa012bd53e48791a6c8a72"}}],"filters":[{"key":{"name":"vegaprotocol.builtin.timestamp","type":"TYPE_TIMESTAMP"},"conditions":[{"operator":"OPERATOR_EQUALS","value":"1686016250"}]}]}}}},"dataSourceSpecBinding":{"settlementDataProperty":"oracle.test.settlement7370C","tradingTerminationProperty":"vegaprotocol.builtin.timestamp"}}},"marginCalculator":{"scalingFactors":{"searchLevel":1.1,"initialMargin":1.2,"collateralRelease":1.4}},"logNormalRiskModel":{"riskAversionParameter":0.001,"tau":0.00011407711613050422,"params":{"r":0.016,"sigma":1.5}}},"decimalPlaces":"5","fees":{"factors":{"makerFee":"0.004","infrastructureFee":"0.001","liquidityFee":"0"}},"openingAuction":{"duration":"13"},"priceMonitoringSettings":{"parameters":{}},"liquidityMonitoringParameters":{"targetStakeParameters":{"timeWindow":"10","scalingFactor":5},"triggeringRatio":"0","auctionExtension":"1"},"tradingMode":"TRADING_MODE_NO_TRADING","state":"STATE_PROPOSED","marketTimestamps":{"proposed":"1686016209415381094","pending":"1686016209415381094","open":"1686016209415381107"},"positionDecimalPlaces":"5","lpPriceRange":"1","linearSlippageFactor":"0.01","quadraticSlippageFactor":"0"},"version":1,"chainId":"testnet-001","txHash":"B21559E0F8AED77FE094CA1067FC1E42CE4B567F9812702FCAF83A769CF21F0D"}
{"id":"4123-31","block":"9C73D94B0B0950451E45BBFBA6E4EE6D563709BB235FF48FFF86EAC6B743A223","type":"BUS_EVENT_TYPE_MARKET_UPDATED","marketUpdated":{"id":"b0974651966033ccf885205482a7cf1af3a2450e52e6648c8e1d7bbc714c53d1","tradableInstrument":{"instrument":{"code":"CRYPTO:VEGA CORE SYS TEST","name":"Futures System-Tests Market","metadata":{"tags":["asset_class:fx/crypto","product:futures"]},"future":{"settlementAsset":"606189f865f23d5ca7429fbd3b186b1578b6e3551ab3561b08c1aace7cbc5a5b","quoteName":"USD","dataSourceSpecForSettlementData":{"id":"44f5b806f74bc593181a1704b0e7c1e5245f2176c5c85fdd7b524fbf1e8972bd","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"5aafa77b998573d6d6e1cacc776b5e743b8adfe85eaa012bd53e48791a6c8a72"}}],"filters":[{"key":{"name":"oracle.test.settlement7370C","type":"TYPE_INTEGER","numberDecimalPlaces":"3"},"conditions":[{"operator":"OPERATOR_GREATER_THAN_OR_EQUAL","value":"0"}]}]}}}},"dataSourceSpecForTradingTermination":{"id":"00795fcb5fc877355dc738e87dccfb570ef558fa1b8e017dc406791ed9759d39","data":{"external":{"oracle":{"signers":[{"pubKey":{"key":"5aafa77b998573d6d6e1cacc776b5e743b8adfe85eaa012bd53e48791a6c8a72"}}],"filters":[{"key":{"name":"vegaprotocol.builtin.timestamp","type":"TYPE_TIMESTAMP"},"conditions":[{"operator":"OPERATOR_EQUALS","value":"1686016250"}]}]}}}},"dataSourceSpecBinding":{"settlementDataProperty":"oracle.test.settlement7370C","tradingTerminationProperty":"vegaprotocol.builtin.timestamp"}}},"marginCalculator":{"scalingFactors":{"searchLevel":1.1,"initialMargin":1.2,"collateralRelease":1.4}},"logNormalRiskModel":{"riskAversionParameter":0.001,"tau":0.00011407711613050422,"params":{"r":0.016,"sigma":1.5}}},"decimalPlaces":"5","fees":{"factors":{"makerFee":"0.004","infrastructureFee":"0.001","liquidityFee":"0"}},"openingAuction":{"duration":"13"},"priceMonitoringSettings":{"parameters":{}},"liquidityMonitoringParameters":{"targetStakeParameters":{"timeWindow":"10","scalingFactor":5},"triggeringRatio":"0","auctionExtension":"1"},"tradingMode":"TRADING_MODE_NO_TRADING","state":"STATE_PROPOSED","marketTimestamps":{"proposed":"1686016209415381094","pending":"1686016209415381094","open":"1686016209415381107"},"positionDecimalPlaces":"5","lpPriceRange":"1","linearSlippageFactor":"0.01","quadraticSlippageFactor":"0"},"version":1,"chainId":"testnet-001","txHash":"B21559E0F8AED77FE094CA1067FC1E42CE4B567F9812702FCAF83A769CF21F0D"}
```

**Comment by EVODelavega** [comment] 2023-06-08 11:54
Closing as not a bug. For markets in proposed state, a new market is created. Creating this market will already emit `MarketCreated`, and `MarketUpdated` events. Arguably, this is duplication, but one could argue a new market being created is in itself an update to _"markets"_ as a concept or a change from `nil` to `Market{actual data}`, and thus the market update event stream should contain this information.

The other 3 events are due to the fact that we propagate certain network parameters to this new market. The functions that handle this can be called manually (as is the case when creating a new market), but are also triggered callbacks for when these network parameters are changed through governance. These functions essentially work the same in both cases, and because their job is to update the market, they will send a market updated event. An example of such a function:

```go
func (m *Market) OnFeeFactorsMakerFeeUpdate(ctx context.Context, d num.Decimal) error {
	m.fee.OnFeeFactorsMakerFeeUpdate(d)
	m.mkt.Fees.Factors.MakerFee = d
	m.broker.Send(events.NewMarketUpdatedEvent(ctx, *m.mkt))

	return nil
}
```

The network parameters that trigger a market updated event are:

* Margin scaling factors
* maker fee factors (example above)
* Infrastructure fee factors

Giving us exactly 3 additional market updated events when creating the market, for a total of 4. This behaviour is expected, and is the result of the netparam update triggers working correctly.

**Closed** 2023-06-08 11:54 UTC
Labels: bug
