### ISSUE TITLE
Panic on core vega when starting a new datanode

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#6878] opened 2022-11-21 12:52 UTC
Received a panic when starting a new datanode.

Scenario:
Start a new datanode without initialising from dehistory i.e. the datanode will expect event from block zero.
However start the code vega node attached to this datanode from a latest snapshot.

The datanode started correct fails to start up with the correct error message.

But we also see a panic on the core vega node which is unexpected.

The node set to look into is - [testnet-nodeset-full-4-full](https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28230/artifact/testnet/logs/testnet-nodeset-full-4-full)

Jenkins Run 1:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28202/artifact/testnet/logs/testnet-nodeset-full-4-full/

Panic on Jenkins:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28202/artifact/testnet/logs/testnet-nodeset-full-4-full/vega-full-4.stderr-2022-11-21T11%3A49%3A36Z.log/*view*/

Jenkins Run 2:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28230/artifact/testnet/logs/testnet-nodeset-full-4-full/

Panic on Jenkins:
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/28230/artifact/testnet/logs/testnet-nodeset-full-4-full/vega-full-4.stderr-2022-11-21T12%3A38%3A36Z.log/*view*/

System Tests Branch - **feat_dehistory_tests_4**
System Tests Marker - **dehistory_datanodes**

**Comment by wwestgarth** [comment] 2022-11-21 13:03
Panic looks to be in tendermint during shutdown, so is likely the same as:
https://github.com/vegaprotocol/vega/issues/6680

**Comment by ettec** [comment] 2022-11-21 14:00
datanode is closing due to "block height on begin block, 261, is too high, the height of the last processed block is 0"  this is expected behaviour.  So either the core is not being reset, or its not expected to be reset, in which it could be that the datanode is being wiped at startup when perhaps it shouldn't be?

**Comment by MuthuVega** [comment] 2022-11-21 16:58
The expected behaviour is fine - but there is a panic , do we need to address that ?

**Comment by ettec** [comment] 2022-11-21 17:03
duplicate of #6680

**Closed by ettec** 2022-11-21 17:03 UTC
Labels: bug
