### ISSUE TITLE
Implement UpdateAsset proposal

### ISSUE THREAD

**Issue by jeremyletang** [vegaprotocol/vega#5281] opened 2022-04-26 08:26 UTC
A new asset proposal needs to be implemented in order to modify assets.

Specs here: https://github.com/vegaprotocol/specs-internal/pull/1048

**Comment by gordsport** [comment] 2022-08-05 13:52
Closing as a duplicate of work in progress/done

**Closed by gordsport** 2022-08-05 13:52 UTC
