### ISSUE TITLE
[Bug]: Soak test failure on network history

### ISSUE THREAD

**Issue by Sohill-Patel** [vegaprotocol/vega#9333] opened 2023-09-08 13:51 UTC
### Problem encountered

```
panic: block.AppHash does not match AppHash after replay. Got 98B82FE004016BAA095CE991A06C8D786D0229EA298671876AB8D79A5E341034, expected 0926D3D1AD9676C1D9EFEE595EA3A4E8F41F3C8CF43B2B60ED8F7C36870700F8.

Block: Block{
  Header{
    Version:        {11 1}
    ChainID:        testnet-001
    Height:         486
    Time:           2023-09-08 12:57:38.027618664 +0000 UTC
    LastBlockID:    F1444A97F4E6A8E128D78E376F06A404ACD2A859DF044E5B2B0EF6FB67A8FECE:1:B942A6D5E99D
    LastCommit:     247EBB4A7DB85F0FEF09BA8908994299F4619A9FC0B3A9F40470E6E5D0AC9421
    Data:           E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Validators:     673730AFA10DF75C588590A6755A3657C86CACC61A2A539EB1284245F718EA3C
    NextValidators: 673730AFA10DF75C588590A6755A3657C86CACC61A2A539EB1284245F718EA3C
    App:            0926D3D1AD9676C1D9EFEE595EA3A4E8F41F3C8CF43B2B60ED8F7C36870700F8
    Consensus:      C8CD39A92B22597AC33565A59990B4D1E440B15621B5E932D1D5B39A8F45E9DB
    Results:        E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Evidence:       E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Proposer:       D9CFEEA1DE084E14A40898A2452248CBBBFA5DCF
  }#8914EB1F9ACE6625E00C79DCE01E9F677278D7490D9588DA153DE16156535D18
  Data{
    
  }#E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  EvidenceData{
    
  }#E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  Commit{
    Height:     485
    Round:      0
    BlockID:    F1444A97F4E6A8E128D78E376F06A404ACD2A859DF044E5B2B0EF6FB67A8FECE:1:B942A6D5E99D
    Signatures:
      CommitSig{933689B612C0 by 6757D826C8C2 on 2 @ 2023-09-08T12:57:38.126067132Z}
      CommitSig{D4B7FA3B3B26 by D9CFEEA1DE08 on 2 @ 2023-09-08T12:57:38.027618664Z}
  }#247EBB4A7DB85F0FEF09BA8908994299F4619A9FC0B3A9F40470E6E5D0AC9421
}#8914EB1F9ACE6625E00C79DCE01E9F677278D7490D9588DA153DE16156535D18
```

### Observed behaviour

soak test failure

### Expected behaviour

soak test pass

### Steps to reproduce

```bash
1. Run test for `test_lp_fee_account_in_net_history` on ST branch `sla-network-history1`
2. on vega develop
```

### Software version

dev branch

### Failing test

test_lp_fee_account_in_net_history

### Jenkins run

https://jenkins.vega.rocks/job/common/job/system-tests-wrapper/6135/

**Comment by jeremyletang** [comment] 2023-09-11 17:46
Is this still reproducible?

**Comment by gordsport** [comment] 2023-09-12 08:01
@jeremyletang @Sohill-Patel - the soak tests pass on this when rerunning the ST branch `sla-network-history1` with the latest core develop:

https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/7527/pipeline/577

**Comment by gordsport** [comment] 2023-09-12 08:30
Reopened as this issue seems to still persist:

- https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/7566/pipeline/575

**Comment by wwestgarth** [comment] 2023-09-12 12:57
This was fixed by https://github.com/vegaprotocol/vega/pull/9360

I ran the test against the new commit twice, and although it still fails due to some test-code timing issue, there are no longer issues with the snapshots:
https://jenkins.vega.rocks/blue/organizations/jenkins/common%2Fsystem-tests-wrapper/detail/system-tests-wrapper/7796/tests

**Closed by wwestgarth** 2023-09-12 12:57 UTC
Labels: bug, liquidity-sla
