### ISSUE TITLE
[Feature]: change network parameter market.liquidity.probabilityOfTrading.tau.scaling bound from 1 to 0

### ISSUE THREAD

**Issue by Jiajia-Cui** [vegaprotocol/vega#10444] opened 2024-01-18 14:32 UTC
## Feature Overview
change the tau.scaling bound so it can be smaller than 1

This has been amended to change the how the probability of trading is distributed, so we want to reward more to traders who places “better” orders (i.e. orders closer to the mid) .

## Specs
- [spec](https://github.com/vegaprotocol/specs/pull/2134/files)

**Comment by gordsport** [comment] 2024-01-18 14:59
closing as a duplicate of: 
- https://github.com/vegaprotocol/vega/issues/10286

**Closed by gordsport** 2024-01-18 14:59 UTC
Labels: feature, duplicate
