### ISSUE TITLE
Governance transfers configured to executed during a protocol upgrade do not complete

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8629] opened 2023-06-28 20:37 UTC
Evidence here
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/79065/

Test proposes 4 governance transfers, one of which is configured to start transferring during the protocol upgrade process.
After network is restored, the test checks all transfers to ensure reached a done state and funds are transferred.

The transfer occurring at the same time as the upgrade does not produce a done event when network comes up, only the original pending can be found, all other transfers can be discovered.

**Comment by ze97286** [comment] 2023-06-28 22:53
this is not a bug. It's an issue with the test, more specifically with how the scanners are registered if I had to guess. Look at the following:

The transfer is setup to start (and end) in epoch  38 (which is going to be after the upgrade):
```
{"id":"313-5","block":"F74FCD36B2530805A1C86DF244C4376CAD36607FDE9A7F32F57A290A824A072B","type":"BUS_EVENT_TYPE_TRANSFER","transfer":{"id":"389413ea95ecc191136bfb5e06c5f99582f8ec9fcb5046c3ee538d1465f8da6d","from":"0000000000000000000000000000000000000000000000000000000000000000","fromAccountType":"ACCOUNT_TYPE_GLOBAL_REWARD","to":"f13d6f656c954c59c135ebe7c77016976a47644aee492c8ed4ceed87b3b9022d","toAccountType":"ACCOUNT_TYPE_GENERAL","asset":"16e41e75f4e57d0ffe9980dc875340b310a3fa711220983dbfb8bd16ca39556d","amount":"0","reference":"77FA2BD7EE","status":"STATUS_PENDING","timestamp":"1687984104805399086","recurringGovernance":{"startEpoch":"38","endEpoch":"38"}},"version":1,"chainId":"testnet-001","txHash":"F74FCD36B2530805A1C86DF244C4376CAD36607FDE9A7F32F57A290A824A072B"}
```

epoch 38 starts on block 367 and ends in block 374:
```
2023-06-28T20:29:07.742Z	INFO	core.protocol.spam	spam/engine.go:215	Spam protection OnEpochEvent called	{"epoch": 38}
2023-06-28T20:29:07.742Z	INFO	tendermint	state/execution.go:333	executed block	{"height": 367, "num_valid_txs": 0, "num_invalid_txs": 0}
```

The protocol upgrade happened in block 363:
```
{
"id": "364-1",
"block": "1934BCF315D3631CFF673ECF3BAAC395D0872D0550C4F25F8A0E5831C1627F10",
"type": "BUS_EVENT_TYPE_PROTOCOL_UPGRADE_STARTED",
"protocolUpgradeStarted": {
"lastBlockHeight": "363"
},
"version": 1,
"chainId": "testnet-001",
"txHash": "1934BCF315D3631CFF673ECF3BAAC395D0872D0550C4F25F8A0E5831C1627F10"
}
```

However if you look at the begin block scanners you'll see that you're missing a bunch of blocks from after the protocol upgrade:
```
{"id":"361-1","block":"263B9E80EFBFE3197C2A74029A348CB989C2AC1B3843AAD275FE934C56C156AF","type":"BUS_EVENT_TYPE_BEGIN_BLOCK","beginBlock":{"height":"361","timestamp":"1687984135772358503","hash":"263b9e80efbfe3197c2a74029a348cb989c2ac1b3843aad275fe934c56c156af"},"version":1,"chainId":"testnet-001","txHash":"263B9E80EFBFE3197C2A74029A348CB989C2AC1B3843AAD275FE934C56C156AF"}
{"id":"362-1","block":"242054B8EE45ACB6047B480AFF69E85210D2FC06A9C8F78660DBBAE2F3661F7B","type":"BUS_EVENT_TYPE_BEGIN_BLOCK","beginBlock":{"height":"362","timestamp":"1687984136179682817","hash":"242054b8ee45acb6047b480aff69e85210d2fc06a9c8f78660dbbae2f3661f7b"},"version":1,"chainId":"testnet-001","txHash":"242054B8EE45ACB6047B480AFF69E85210D2FC06A9C8F78660DBBAE2F3661F7B"}
{"id":"363-1","block":"F0893D4B9D10AC2A18B502BFE9C05355812372135FF798D2A4C4B6600C8D9A18","type":"BUS_EVENT_TYPE_BEGIN_BLOCK","beginBlock":{"height":"363","timestamp":"1687984136649203334","hash":"f0893d4b9d10ac2a18b502bfe9c05355812372135ff798d2a4c4b6600c8d9a18"},"version":1,"chainId":"testnet-001","txHash":"F0893D4B9D10AC2A18B502BFE9C05355812372135FF798D2A4C4B6600C8D9A18"}

SCANNERS WERE RESET AT THIS POINT FOR REASON: protocol upgrade
{"id":"376-1","block":"4A1277B9CA1EDDD756983110D655C4EA7D0F3B32BC87AE72205219A49F127932","type":"BUS_EVENT_TYPE_BEGIN_BLOCK","beginBlock":{"height":"376","timestamp":"1687984154427956558","hash":"4a1277b9ca1eddd756983110d655c4ea7d0f3b32bc87ae72205219a49f127932"},"version":1,"chainId":"testnet-001","txHash":"4A1277B9CA1EDDD756983110D655C4EA7D0F3B32BC87AE72205219A49F127932"}
{"id":"377-1","block":"6BB81D024DD68D8F7E8AAFF50D9C1E317F75723B3CCDA317D3E10758C7BE2BEB","type":"BUS_EVENT_TYPE_BEGIN_BLOCK","beginBlock":{"height":"377","timestamp":"1687984155270529045","hash":"6bb81d024dd68d8f7e8aaff50d9c1e317f75723b3ccda317d3e10758c7be2beb"},"version":1,"chainId":"testnet-001","txHash":"6BB81D024DD68D8F7E8AAFF50D9C1E317F75723B3CCDA317D3E10758C7BE2BEB"}
{"id":"378-1","block":"02040D141EFD5B736ED266F0FBE0D117C47D20D34EE4A1EE100ECBC600FFB4AE","type":"BUS_EVENT_TYPE_BEGIN_BLOCK","beginBlock":{"height":"378","timestamp":"1687984156123850472","hash":"02040d141efd5b736ed266f0fbe0d117c47d20d34ee4a1ee100ecbc600ffb4ae"},"version":1,"chainId":"testnet-001","txHash":"02040D141EFD5B736ED266F0FBE0D117C47D20D34EE4A1EE100ECBC600FFB4AE"}
```

in particular you don't have block 374 where the recurring transfer had happened and changed to done. The transfer does happen and does change to done.

**Comment by gordsport** [comment] 2023-07-14 06:49
closing as no update from above comment

**Closed by gordsport** 2023-07-14 06:49 UTC
Labels: bug, governance, protocol-upgrade
