### ISSUE TITLE
SLA runtime error: invalid memory address or nil pointer dereference (goroutine 225)

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#9067] opened 2023-08-14 15:42 UTC
```
2023-08-14T16:38:39.118+0100	ERROR	tendermint	consensus/state.go:732	CONSENSUS FAILURE!!!	{"err": "runtime error: invalid memory address or nil pointer dereference", "stack": "goroutine 225 [running]:\nruntime/debug.Stack()
/opt/homebrew/Cellar/go@1.19/1.19.10/libexec/src/runtime/debug/stack.go:24 +0x64\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2()
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:732 +0x44\npanic({0x107caa040, 0x10a0ecae0})
/opt/homebrew/Cellar/go@1.19/1.19.10/libexec/src/runtime/panic.go:884 +0x204\ncode.vegaprotocol.io/vega/core/execution/common.(*MarketLiquidity).CancelLiquidityProvision(0x14012bf8b40, {0x1082f7e70, 0x14013d08ab0}, {0x140181b4800, 0x40})
/Users/paulwebb/repos/vega/core/execution/common/liquidity_provision.go:569 +0xbc\ncode.vegaprotocol.io/vega/core/execution/future.(*Market).CancelLiquidityProvision(0x107c67ea0?, {0x1082f7e70?, 0x14013d08ab0?}, 0x40?, {0x140181b4800?, 0x178?})
/Users/paulwebb/repos/vega/core/execution/future/liquidity_provision.go:55 +0x64\ncode.vegaprotocol.io/vega/core/execution.(*Engine).CancelLiquidityProvision(0x1400034f180, {0x1082f7e70, 0x14013d08ab0}, 0x14019d6f850, {0x140181b4800, 0x40})
/Users/paulwebb/repos/vega/core/execution/engine.go:1207 +0x390\ncode.vegaprotocol.io/vega/core/processor.(*App).DeliverCancelLiquidityProvision(0x1400123a300, {0x1082f7e70, 0x14013d08ab0}, {0x10831e790, 0x14011755fc0})
/Users/paulwebb/repos/vega/core/processor/abci.go:1674 +0x1d8\ncode.vegaprotocol.io/vega/core/processor.(*App).SendTransactionResult.func1({0x1082f7e70, 0x14013d08ab0}, {0x10831e790, 0x14011755fc0})
/Users/paulwebb/repos/vega/core/processor/abci.go:486 +0x40\ncode.vegaprotocol.io/vega/core/blockchain/abci.(*App).DeliverTx(0x140003e6420, {{0x1400e753c80, 0x178, 0x178}})
/Users/paulwebb/repos/vega/core/blockchain/abci/abci.go:140 +0x600\ncode.vegaprotocol.io/vega/cmd/vega/commands/node.(*appW).DeliverTx(0x14016036ea0?, {{0x1400e753c80?, 0x20?, 0xb?}})
/Users/paulwebb/repos/vega/cmd/vega/commands/node/app_wrapper.go:37 +0x4c\ngithub.com/tendermint/tendermint/abci/client.(*localClient).DeliverTxAsync(0x140003bede0, {{0x1400e753c80?, 0x140003bede0?, 0x140005d22f8?}})
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/abci/client/local_client.go:93 +0xf0\ngithub.com/tendermint/tendermint/proxy.(*appConnConsensus).DeliverTxAsync(0x14016036ea0?, {{0x1400e753c80?, 0x20?, 0xb?}})
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/proxy/app_conn.go:85 +0x2c\ngithub.com/tendermint/tendermint/state.execBlockOnProxyApp({0x1082f6190?, 0x1400038ccd8}, {0x10830cc80, 0x140002754f0}, 0x1400ef8a5a0, {0x10831f438, 0x140003d8048}, 0xeb7?)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:320 +0x6f4\ngithub.com/tendermint/tendermint/state.(*BlockExecutor).ApplyBlock(_, {{{0xb, 0x1}, {0x140018801f0, 0x7}}, {0x14001880200, 0xb}, 0x1, 0xeb7, {{0x14015157a40, ...}, ...}, ...}, ...)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/state/execution.go:140 +0xe4\ngithub.com/tendermint/tendermint/consensus.(*State).finalizeCommit(0x14001609880, 0xeb8)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1661 +0x94c\ngithub.com/tendermint/tendermint/consensus.(*State).tryFinalizeCommit(0x14001609880, 0xeb8)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1570 +0x288\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit.func1()
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1505 +0xa0\ngithub.com/tendermint/tendermint/consensus.(*State).enterCommit(0x14001609880, 0xeb8, 0x0)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1543 +0xb8c\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0x14001609880, 0x14011ad0c80, {0x140019f0450, 0x28})
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:2165 +0x1678\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0x14001609880, 0x14011ad0c80, {0x140019f0450?, 0x14016701c00?})
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:1963 +0x28\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0x14001609880, {{0x1082d2d60?, 0x1401714edb0?}, {0x140019f0450?, 0x0?}})
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:861 +0x108\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0x14001609880, 0x0)
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:768 +0x2bc\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart
/Users/paulwebb/go/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/state.go:379 +0xf4\n"}
```

**Comment by vega-paul** [comment] 2023-08-14 15:44
[vega-validator-1.stdout-2023-08-14T15:58:32+01:00.log](https://github.com/vegaprotocol/vega/files/12336933/vega-validator-1.stdout-2023-08-14T15.58.32%2B01.00.log)

**Comment by gordsport** [comment] 2023-08-14 15:52
possible duplicate of: 
- https://github.com/vegaprotocol/vega/issues/9066

**Closed** 2023-08-14 16:38 UTC
Labels: crasher, bug, liquidity-sla
