### ISSUE TITLE
Error when starting datanode from dehistory

### ISSUE THREAD

**Issue by MuthuVega** [vegaprotocol/vega#6971] opened 2022-11-29 09:31 UTC
Receive this error quite frequently when trying to start a datanode from dehistory.

`failed to initialise datanode from decentralized history:failed to fetch history blocks:failed to fetch history:could not get file with CID, connected peer addresses ,/ip4/127.0.0.1/tcp/4025,/ip4/127.0.0.1/tcp/4075,/ip6/::1/tcp/4055,/ip4/127.0.0.1/tcp/4045,/ip4/10.100.0.246/tcp/4035: context deadline exceeded`

**Jenkins Runs:**
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/30522/
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/30524/
https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/30525/

**Jenkins Error messages:**
[https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/30522/artifact/testnet[…]ll/data-node-3.stderr-2022-11-28T18%3A17%3A46Z.log/*view*/](https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/30522/artifact/testnet/logs/testnet-nodeset-full-3-full/data-node-3.stderr-2022-11-28T18%3A17%3A46Z.log/*view*/)
[https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/30524/artifact/testnet[…]ll/data-node-8.stderr-2022-11-28T18%3A24%3A36Z.log/*view*/](https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/30524/artifact/testnet/logs/testnet-nodeset-full-8-full/data-node-8.stderr-2022-11-28T18%3A24%3A36Z.log/*view*/)
[https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/30525/artifact/testnet[…]ll/data-node-5.stderr-2022-11-28T18%3A20%3A16Z.log/*view*/](https://jenkins.ops.vega.xyz/job/common/job/system-tests-wrapper/30525/artifact/testnet/logs/testnet-nodeset-full-5-full/data-node-5.stderr-2022-11-28T18%3A20%3A16Z.log/*view*/)

**Comment by ettec** [comment] 2022-12-05 12:11
duplicate of #7007

**Closed by ettec** 2022-12-05 12:11 UTC
Labels: critical, bug, dehistory
