### ISSUE TITLE
Snapshot load panic - AppHash does not match AppHash after replay

### ISSUE THREAD

**Issue by vega-paul** [vegaprotocol/vega#8107] opened 2023-04-07 08:14 UTC
https://jenkins.ops.vega.xyz/job/common/job/snapshot-soak-tests/4537/artifact/artifacts/testnet/err-node-0.log

```
panic: block.AppHash does not match AppHash after replay. Got 6F52CA595BD7ED0703F6B652F18654C305A8EB6E51EA67E49071C9C5865B9ED5, expected 11B5E65E84D8F8AEC1D402449CF070D41256998088DCA3817275B7D2AFF3412F.

Block: Block{
  Header{
    Version:        {11 1}
    ChainID:        testnet-001
    Height:         2
    Time:           2023-04-06 21:03:34.918661795 +0000 UTC
    LastBlockID:    79BBE929F6E71FA9A6F7A3B3FE42B18B6497190573C075E4E39CDF97B1BF2663:1:5013141B8F79
    LastCommit:     2E1BFD0321C481D274BF998FACAC58784D071BC1B7BE3BBF075686A431D8B514
    Data:           E2DE4C603C858A5D0BFA8E6AE73076AB20B089119509AFAB1426C599C1515B9D
    Validators:     980E642AD8C6DF6E17514FDCA01E5C96CBF8619D28658E8D7243EEADDF3BB12E
    NextValidators: 980E642AD8C6DF6E17514FDCA01E5C96CBF8619D28658E8D7243EEADDF3BB12E
    App:            11B5E65E84D8F8AEC1D402449CF070D41256998088DCA3817275B7D2AFF3412F
    Consensus:      C8CD39A92B22597AC33565A59990B4D1E440B15621B5E932D1D5B39A8F45E9DB
    Results:        E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Evidence:       E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Proposer:       E1A85A3092F06D5B2061689EFC7DF4A3E6507C2D
  }#B1EC490813900611D8BA78E9EF3989CF966CB47D3BE71745855F24D291EEA8C1
  Data{
    4E4A637A386FC20D9F4BC397A78D8B742F8BEF0EB17284D85C7ED1895FAE654A (661 bytes)
  }#E2DE4C603C858A5D0BFA8E6AE73076AB20B089119509AFAB1426C599C1515B9D
  EvidenceData{
    
  }#E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  Commit{
    Height:     1
    Round:      0
    BlockID:    79BBE929F6E71FA9A6F7A3B3FE42B18B6497190573C075E4E39CDF97B1BF2663:1:5013141B8F79
    Signatures:
      CommitSig{FE68180658B2 by B04AFA7C87F7 on 2 @ 2023-04-06T21:03:35.011096696Z}
      CommitSig{0EF79F78AC4F by E1A85A3092F0 on 2 @ 2023-04-06T21:03:34.918661795Z}
  }#2E1BFD0321C481D274BF998FACAC58784D071BC1B7BE3BBF075686A431D8B514
}#B1EC490813900611D8BA78E9EF3989CF966CB47D3BE71745855F24D291EEA8C1
 [recovered]
	panic: block.AppHash does not match AppHash after replay. Got 6F52CA595BD7ED0703F6B652F18654C305A8EB6E51EA67E49071C9C5865B9ED5, expected 11B5E65E84D8F8AEC1D402449CF070D41256998088DCA3817275B7D2AFF3412F.

Block: Block{
  Header{
    Version:        {11 1}
    ChainID:        testnet-001
    Height:         2
    Time:           2023-04-06 21:03:34.918661795 +0000 UTC
    LastBlockID:    79BBE929F6E71FA9A6F7A3B3FE42B18B6497190573C075E4E39CDF97B1BF2663:1:5013141B8F79
    LastCommit:     2E1BFD0321C481D274BF998FACAC58784D071BC1B7BE3BBF075686A431D8B514
    Data:           E2DE4C603C858A5D0BFA8E6AE73076AB20B089119509AFAB1426C599C1515B9D
    Validators:     980E642AD8C6DF6E17514FDCA01E5C96CBF8619D28658E8D7243EEADDF3BB12E
    NextValidators: 980E642AD8C6DF6E17514FDCA01E5C96CBF8619D28658E8D7243EEADDF3BB12E
    App:            11B5E65E84D8F8AEC1D402449CF070D41256998088DCA3817275B7D2AFF3412F
    Consensus:      C8CD39A92B22597AC33565A59990B4D1E440B15621B5E932D1D5B39A8F45E9DB
    Results:        E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Evidence:       E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
    Proposer:       E1A85A3092F06D5B2061689EFC7DF4A3E6507C2D
  }#B1EC490813900611D8BA78E9EF3989CF966CB47D3BE71745855F24D291EEA8C1
  Data{
    4E4A637A386FC20D9F4BC397A78D8B742F8BEF0EB17284D85C7ED1895FAE654A (661 bytes)
  }#E2DE4C603C858A5D0BFA8E6AE73076AB20B089119509AFAB1426C599C1515B9D
  EvidenceData{
    
  }#E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855
  Commit{
    Height:     1
    Round:      0
    BlockID:    79BBE929F6E71FA9A6F7A3B3FE42B18B6497190573C075E4E39CDF97B1BF2663:1:5013141B8F79
    Signatures:
      CommitSig{FE68180658B2 by B04AFA7C87F7 on 2 @ 2023-04-06T21:03:35.011096696Z}
      CommitSig{0EF79F78AC4F by E1A85A3092F0 on 2 @ 2023-04-06T21:03:34.918661795Z}
  }#2E1BFD0321C481D274BF998FACAC58784D071BC1B7BE3BBF075686A431D8B514
}#B1EC490813900611D8BA78E9EF3989CF966CB47D3BE71745855F24D291EEA8C1


goroutine 178 [running]:
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1.1()
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:137 +0x59
panic({0x4427040, 0xc000ffdf30})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/tendermint/tendermint/consensus.assertAppHashEqualsOneFromBlock({0xc0002ad780, 0x20, 0x20}, 0xc002a8a5a0)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:515 +0x10d
github.com/tendermint/tendermint/consensus.(*Handshaker).replayBlocks(_, {{{0xb, 0x1}, {0xc001d291a0, 0x7}}, {0xc001d291c0, 0xb}, 0x1, 0x4d, {{0xc001f6e200, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:468 +0x1fd
github.com/tendermint/tendermint/consensus.(*Handshaker).ReplayBlocks(_, {{{0xb, 0x1}, {0xc001d291a0, 0x7}}, {0xc001d291c0, 0xb}, 0x1, 0x4d, {{0xc001f6e200, ...}, ...}, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:393 +0x479
github.com/tendermint/tendermint/consensus.(*Handshaker).Handshake(0xc000f36d90, {0x54b9db0, 0xc00061e340})
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/consensus/replay.go:268 +0x3d4
github.com/tendermint/tendermint/node.doHandshake({_, _}, {{{0xb, 0x1}, {0xc001d291a0, 0x7}}, {0xc001d291c0, 0xb}, 0x1, 0x4d, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/node/node.go:329 +0x1b8
github.com/tendermint/tendermint/node.NewNode(0xc001a64280, {0x5487330, 0xc0002f68c0}, 0xc001b785c0, {0x546b260, 0xc00031f9c8}, 0x0?, 0x0?, 0xc001b78600, {0x548d290, ...}, ...)
	/jenkins/GOPATH/pkg/mod/github.com/vegaprotocol/cometbft@v0.34.28-0.20230322133204-3d8588de736e/node/node.go:779 +0x597
code.vegaprotocol.io/vega/core/blockchain/abci.NewTmNode({{0x0}, 0x1, 0x1, 0x0, 0x0, {0xc0019918d0, 0xa}, {{0x0}, {0xc000497bc0, 0x15}}, ...}, ...)
	/jenkins/workspace/common/system-tests-wrapper/vega/core/blockchain/abci/tm_node.go:83 +0x705
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).startABCI(0xc0003e9000, 0x0?, {0x54b3360, 0xc00048c520}, {0x7ffc3f8f74c9, 0x10}, {0x0?, 0x0?}, {0x0, 0x0})
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:412 +0x1b6
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).startBlockchain(0xc0003e9000, 0x0?, {0x7ffc3f8f74c9?, 0x0?}, {0x0, 0x0}, {0x0, 0x0})
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:299 +0x3ab
code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run.func1()
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:140 +0x90
created by code.vegaprotocol.io/vega/cmd/vega/commands/node.(*Command).Run
	/jenkins/workspace/common/system-tests-wrapper/vega/cmd/vega/commands/node/node.go:131 +0x66f
```

**Comment by wwestgarth** [comment] 2023-04-13 09:14
So this is not a core issue the problem is that the vega version used to replay the chain for the snapshot-soak tests mismatches with the one that created the chain.

I think the reason why this has started happening is due to this change: https://github.com/vegaprotocol/vega/pull/8098

Now `+dev` is added to the version we hit this code:
```
if strings.HasSuffix(cliVersion, "+dev") {
		splatHash := strings.Split(cliVersionHash, "-")

		// Verifying if splitting the version hash gave results.
		if len(splatHash) == 0 {
			return finalVersion
		}

		// Verifying if there is a commit hash.
		if splatHash[0] != "" {
			finalVersion = finalVersion + "." + splatHash[0][:8]
		}

		// Anything left from the splitting is appended as build tags behind.
		for i := 1; i < len(splatHash); i++ {
			finalVersion = finalVersion + "." + splatHash[i]
		}
	}
```

which is slapping a `.modified` to the end of the version for the binary used  _for the soak tests_ but the binary used to generate the chain originally does not have `.modified`. Before this change the binary we pulled for the soak tests didn't have a `+dev` and so we never added the `.modified`.

The system test job builds a lot of vega binaries. I don't know which one the soak-tests pull in but I guess its the wrong one?

Closing this because there is this devops ticket for it: https://github.com/vegaprotocol/devops-infra/issues/1836

**Closed by wwestgarth** 2023-04-13 09:14 UTC
Labels: crasher, bug, snapshots
