### ISSUE TITLE
Dont think notional requirement API is working

### ISSUE THREAD

**Issue by JonRay15** [vegaprotocol/vega#10914] opened 2024-03-16 10:47 UTC
## Bug Description

There is a transfer / game active as below:

```
"node": {
            "transfer": {
              "id": "6e32ba282a3168f05746714a05a78f201b28a73e6a9c3e3faaa1c2f19289f574",
              "gameId": "f1168051a22e59b925d1d26d905979bab22faa775b1b2fd754981ae75d13f5cb",
              "from": "69464e35bcb8e8a2900ca0f87acaf252d50cf2ab2fc73694845a16b7c8a0dc6f",
              "fromAccountType": "ACCOUNT_TYPE_GENERAL",
              "to": "network",
              "toAccountType": "ACCOUNT_TYPE_REWARD_AVERAGE_POSITION",
              "asset": {
                "id": "0c76ff735d7f8ec464d424b0362eb623cc46511b6dae7e75dd1ee84decbfceb8",
                "symbol": "USD-CAP"
              },
              "amount": "1000000000",
              "reference": "AVG position",
              "status": "STATUS_PENDING",
              "timestamp": "2024-03-16T09:31:38.392978Z",
              "kind": {
                "startEpoch": 13173,
                "endEpoch": 13346,
                "dispatchStrategy": {
                  "dispatchMetric": "DISPATCH_METRIC_AVERAGE_POSITION",
                  "dispatchMetricAssetId": "0c76ff735d7f8ec464d424b0362eb623cc46511b6dae7e75dd1ee84decbfceb8",
                  "marketIdsInScope": [
                    "6291cac44e47d8b89af0b6230296ea8024a30d7fa6630a4c1a1ce784df9e7c4f"
                  ],
                  "entityScope": "ENTITY_SCOPE_TEAMS",
                  "individualScope": "INDIVIDUAL_SCOPE_UNSPECIFIED",
                  "teamScope": null,
                  "nTopPerformers": "0.5",
                  "stakingRequirement": "",
                  "notionalTimeWeightedAveragePositionRequirement": "25000000000",
                  "windowLength": 1,
                  "lockPeriod": 0,
                  "distributionStrategy": "DISTRIBUTION_STRATEGY_RANK",
                  "rankTable": [
                    {
                      "startRank": 1,
                      "shareRatio": 3
                    }
                  ]
                }
              },
              "reason": null
            },
            "fees": [
              {
                "transferId": "6e32ba282a3168f05746714a05a78f201b28a73e6a9c3e3faaa1c2f19289f574",
                "amount": "1000000",
                "epoch": 13174
              }
            ]
          }
        },
```

So it should have a requirement of 25k ... which the FE reflects.

![image](https://github.com/vegaprotocol/vega/assets/89918817/a0556fa4-2375-4c22-bcaa-5d594a9bc00b)

I have done a trade on the necessary market with this key: 89fd87b86727fa4d9ab06b9f4e64b51c9b07055e8a0c8f0bc40f0a249e321525

And I have waited an epoch as I assume you need to.

Then I am running this query:

```
query notionalRequired{
  timeWeightedNotionalPosition(assetId:"0c76ff735d7f8ec464d424b0362eb623cc46511b6dae7e75dd1ee84decbfceb8", partyId:"89fd87b86727fa4d9ab06b9f4e64b51c9b07055e8a0c8f0bc40f0a249e321525", gameId:"f1168051a22e59b925d1d26d905979bab22faa775b1b2fd754981ae75d13f5cb"){    
  	assetId
  	partyId
  	gameId
   	epoch
    timeWeightedNotionalPosition
  }
}
```

But I am getting this back:

```
{
  "errors": [
    {
      "message": "failed to get time weighted notional position",
      "path": [
        "timeWeightedNotionalPosition"
      ],
      "extensions": {
        "code": 13,
        "type": "Internal"
      }
    }
  ],
  "data": {
    "timeWeightedNotionalPosition": null
  }
}
```

**Comment by ze97286** [comment] 2024-03-16 11:29
is 89fd87b86727fa4d9ab06b9f4e64b51c9b07055e8a0c8f0bc40f0a249e321525 a member of some team...?

**Comment by ze97286** [comment] 2024-03-16 11:53
I'm gonna say no. 
<img width="947" alt="image" src="https://github.com/vegaprotocol/vega/assets/6655556/18d96491-979b-41c1-8f51-f9a5d2d75ea5">

as opposed to for example: 165860b93e72a53ef19c26174ce7c74597e57d6c2a7090dcc08118dc1121d921:
<img width="1546" alt="image" src="https://github.com/vegaprotocol/vega/assets/6655556/a7611bd9-3909-4c58-ae9d-3b69cf17c37f">

<img width="1728" alt="image" src="https://github.com/vegaprotocol/vega/assets/6655556/e3387808-f964-4ca2-acc8-94ee84981e09">

**Comment by guoguojin** [comment] 2024-03-18 10:10
Following up with Dan after the weekend, it does appear that the notional average position does eventually get propagated to data node correctly and the API is working as expected.

https://vegaprotocol.slack.com/files/U035T0QGUD6/F06PU3U0JS2/screenshot_2024-03-16_at_10.30.41.png

I'm going to close this as not a bug for the time being.

**Closed by guoguojin** 2024-03-18 10:10 UTC
Labels: api, bug
