### ISSUE TITLE
Orderbook stuck with an old price value in the books

### ISSUE THREAD

**Issue by daunatv** [vegaprotocol/vega#10492] opened 2024-01-26 12:15 UTC
## Description

As you can see in the video, orders are still going through but an old price is still visible.
https://vegafairground.eth.limo/#/markets/b936a0e6d67fe7e6477515bbfe636306e239c28ff8ca45cb325e4d04d9bccff1

<img width="897" alt="Screenshot 2024-01-26 at 12 12 03" src="https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/d1352ec5-38d5-46aa-9949-85dffc9da0e3">

https://github.com/vegaprotocol/frontend-monorepo/assets/100769129/d8fed552-32c3-41ae-9aed-f014aef3c126

**Comment by peterbarrow** [comment] 2024-01-30 16:53
Looking into this, the bestBid/bestOffer prices from the market are correct, but the market depth values are crossed when they shouldn't be. The market is active and in continuous mode so that is not the issue. It looks like 5 or so orders have not been removed from the market depth order book which suggests either the logic to handle events is incorrect in the datanode or the events for the orders being removed were not sent. There is no logic in the datanode to check for crossed books because it has no concept of auctions.

**Comment by peterbarrow** [comment] 2024-01-31 11:02
Having gone through the code and available data with Jeremy it looks like the issue is that the amend order which triggered a panic caused the order information that should have been sent out as events to be lost. Therefore the datanode did not get the events it needed to correctly remove old orders from it's cache of the market state. The panic has been resolved and this issue should no longer occur.

**Comment by gordsport** [comment] 2024-02-02 12:56
fixed in

- https://github.com/vegaprotocol/vega/pull/10528

**Closed by gordsport** 2024-02-02 12:56 UTC
Labels: api, bug
