### ISSUE TITLE
Wallet selection casing

### ISSUE THREAD

**Issue by notbot00** [vegaprotocol/vega#6393] opened 2022-10-03 19:47 UTC
# Problem encountered
The wallet name seems to have some inconsistency with case transformation, when it gets sent from the wallet cmd to the wallet api. This trips the request if you have an uppercase wallet name.

# Observed behaviour
Get a "not a valid option" error.

# Expected behaviour
For the connection approval to succeed.

# System response
see the screenshot below

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1. create a wallet with one or more uppercase letter in it
2. start the wallet service
3. send a POST request to the `/api/v2/requests` endpoint with the following payload:
```
{
    "jsonrpc": "2.0",
    "method": "client.connect_wallet",
    "params": {
        "hostname": "vega.xyz"
    },
    "id": "hello" 
}
```
4. go to your terminal, and approve the connection request
5. select the wallet with the upper case letter by typing it in
6. say hi to the error

# Evidence

<img width="681" alt="Screenshot 2022-10-03 at 21 41 55" src="https://user-images.githubusercontent.com/105208209/193664684-abbeffff-7f50-41f6-9323-8f798f19eee7.png">

# Bonus points

It could be a nice improvement to be able to just type in a number for a wallet, instead of the whole name, users possibly could have long wallet names which could make the process more difficult than it has to be (idea/request raised by @barnabee)

**Comment by jeremyletang** [comment] 2022-10-04 12:21
Is this a duplicate of: https://github.com/vegaprotocol/vega/issues/6395 ?

**Comment by gordsport** [comment] 2022-10-04 12:38
Closing as a duplicate. @notbot00 please see linked duplicate and report back if this is different in any way

**Closed** 2022-10-04 12:38 UTC
Labels: Medium, bug, duplicate
