### ISSUE TITLE
Implement the discount/reward application in fee calculation

### ISSUE THREAD

**Issue by ValentinTrinque** [vegaprotocol/vega#9222] opened 2023-08-29 15:25 UTC
Link to spec: https://github.com/vegaprotocol/specs/blob/cosmicelevator/protocol/0029-FEES-fees.md#applying-benefit-factors

**Comment by ze97286** [comment] 2023-09-03 11:32
duplicate of https://github.com/vegaprotocol/vega/issues/9133

**Closed by ze97286** 2023-09-03 11:32 UTC
Labels: referral
