### ISSUE TITLE
[Bug]: numDecimalPlaces seems to be missing in oracle_specs

### ISSUE THREAD

**Issue by pscott31** [vegaprotocol/vega#9520] opened 2023-09-21 17:45 UTC
### Problem encountered

When creating a market define the data sources as part of the market definition. It is stored as part of the 'tradable_instrument' json blob in the database.

We duplicate part of that into the oracle_specs table; but somehow numberDecimalPlaces gets lost:

https://api.n07.testnet.vega.rocks/api/v2/market/be8f6efcb74aab2bdd54f5ea6e2dae6ce436a5aa01e0acc2937032fa2f6fa9ce
vs
https://api.n07.testnet.vega.rocks/api/v2/oracle/spec/8bd64d55a3c79352edfa78e670754e770e9313053a3456c3ebc1382cca472474

![image](https://github.com/vegaprotocol/vega/assets/94362991/c5aabfff-008a-494e-90fb-7b801d45775a)

I don't think it's a large problem but may be confusing

### Observed behaviour

No numdecimalplaces in filters on data source specs on the datanode

### Expected behaviour

there should be

### Steps to reproduce

```bash
1. Submit `xyz` transaction
2. With this payload
3. Query `abc` API
4. Observe the error
```

### Software version

fairground

**Comment by jeremyletang** [comment] 2023-09-21 18:17
seems to be linked to this one: https://github.com/vegaprotocol/vega/issues/9206

**Comment by gordsport** [comment] 2023-09-25 11:27
Closing as a duplicate of #9206 that has been fixed in the PR https://github.com/vegaprotocol/vega/pull/9521

**Closed by gordsport** 2023-09-25 11:27 UTC
Labels: bug, ethereum-oracles
