### ISSUE TITLE
[core] No errorDetails on New Asset proposal that fails validation

### ISSUE THREAD

**Issue by edd** [vegaprotocol/vega#5896] opened 2022-08-15 13:29 UTC
```json
{
      "id": "3d2663fc8d4c8755f8ca33da13ae62941e200223dc88aaebd92c75c710cfc0c5",
      "reference": "",
      "partyId": "a35db5fcbc46962cc8283dbbccc506e82c95a548eddc913da5e35ea173c3b279",
      "state": "STATE_REJECTED",
      "timestamp": "1660569701468783575",
      "terms": {
        "closingTimestamp": "1660572534",
        "enactmentTimestamp": "1660572544",
        "validationTimestamp": "1660569794",
        "newAsset": {
          "changes": {
            "name": "Wrapped eth",
            "symbol": "WETH",
            "totalSupply": "152578093",
            "decimals": "18",
            "quantum": "1",
            "erc20": {
              "contractAddress": "0xc778417E063141139Fce010982780140Aa0cD5Ab",
              "lifetimeLimit": "10",
              "withdrawThreshold": "10"
            }
          }
        }
      },
      "reason": "PROPOSAL_ERROR_NODE_VALIDATION_FAILED",
      "errorDetails": "",
      "rationale": {
        "description": "Add wrapped eth with an incorrect title",
        "hash": "",
        "url": ""
      }
    },
```

Core emmitted: 
> "invalid name, expected(Wrapped eth), got(Wrapped Ether)"

But it does not make it through to REST/GraphQL

**Comment by wwestgarth** [comment] 2022-08-23 09:18
This isn't a data-node issue. 

This ticket https://github.com/vegaprotocol/vega/issues/5817 was supposed to fix this, but it doesn't _quite_. The reason why is because only _validator nodes_ are currently setting the errorDetails when a node-validation proposal fails, and so any non-validator node connected to a data-node isn't getting the error reason and not sending it through. Non-validators do not do the check and so do not hit this code:
```
func (n *nodeProposal) Check() error {
	// always keep the last error
	err := n.checker()
	if err != nil {
		n.err = err.Error()
		return err
	}

	n.err = ""

	return nil
}
```

The problem in fixing this is that currently validator nodes only send a vote is the resource is fine, and we would need to change that so that it can sends a vote if its rejected too along with the reason, so that non-validator nodes can be aware of it. Which is not a quick change.

**Comment by ze97286** [comment] 2022-08-23 11:01
@wwestgarth this seems like a duplicate of https://github.com/vegaprotocol/vega/issues/5473 from your description. Surely #5817 had no intention to address this. Anyhow, I don't think this is something we must have for OT.

**Comment by wwestgarth** [comment] 2022-08-30 14:19
duplicate of https://github.com/vegaprotocol/vega/issues/5896

**Closed by wwestgarth** 2022-08-30 14:19 UTC
Labels: assets, bug, duplicate, governance
