### ISSUE TITLE
Orders subscriptions are not working 

### ISSUE THREAD

**Issue by gordsport** [vegaprotocol/vega#7994] opened 2023-03-27 14:10 UTC
# Problem encountered

Since the introduction of the filtering in https://github.com/vegaprotocol/vega/pull/7893 the orders subscriptions are not working

# Expected behaviour

Orders subscriptions work as they should

**Comment by pscott31** [comment] 2023-03-28 08:13
Dupe of #8001

**Closed by pscott31** 2023-03-28 08:13 UTC
Labels: critical, api, bug
