### ISSUE TITLE
marginsConnection query fails

### ISSUE THREAD

**Issue by mattrussell36** [vegaprotocol/vega#5947] opened 2022-08-19 08:35 UTC
# Problem encountered
When querying for margin levels using `marginsConnection` it fails with `Internal error`

# Observed behaviour
Using the following query results in an error:

Query:
```
{
  party(id: "34b4667dd597d008e0ffd9a5d33c97d261c83269dde39ac1e83430dd79309569") {
    marginsConnection {
      edges {
        node {
          searchLevel
        }
      }
    }
  }
}
```
Error:
```
{
  "errors": [
    {
      "message": "Internal error",
      "path": [
        "party",
        "marginsConnection"
      ],
      "extensions": {
        "code": "10000",
        "detail": "failed to make edge for {1190 147077 161784 367692 397107 2022-08-19 08:29:26.135137 +0000 UTC 2022-08-19 08:29:26.135137 +0000 UTC}: expected account source argument, got:[0xc00056c380]",
        "inner": ""
      }
    }
  ],
  "data": {
    "party": null
  }
}
```

# Expected behaviour
Data is returned without error

## Additional context
Note it also returns data with `party: null`. This is a little weird as this party does indeed exist. If you run the below query it will work. As soon as the `marginConnections` field gets added the party is null and you have error data
```
{
  party(id: "34b4667dd597d008e0ffd9a5d33c97d261c83269dde39ac1e83430dd79309569") {
    positionsConnection {
      edges {
        node{
          realisedPNL
        }
      }
    }
    # Re-add this below and query will error and party will be null
    # marginsConnection {
    #   edges {
    #     node {
    #       maintenanceLevel
    #     }
    #   }
    # }
  }
}
```

**Comment by gordsport** [comment] 2022-08-19 08:49
Hey @ettec 
In speaking with @zale144 we closed 
- https://github.com/vegaprotocol/vega/issues/5196
as you had it covered in work you were doing. Is this the same for this current issue?

**Comment by pscott31** [comment] 2022-08-22 11:12
Hi Matt, the nulls thing is part of how [graphql propagates ](https://dgraph.io/docs/graphql/api/errors/)errors and null values. The gist of it is that because it failed to make a `marginsConnection` and `marginsConnection` is a non-nullable field, has to null the entire party to create a result which fits the schema.

As to the actual error here, I belive this was fixed a while back. I can't reproduce it. I think we can close this issue.

![image](https://user-images.githubusercontent.com/94362991/185907870-edfbd663-12f1-43b1-9cd9-06251253d2f2.png)

**Closed by pscott31** 2022-08-22 11:12 UTC
Labels: margin, bug, DatanodeV2, high
