### ISSUE TITLE
Wallet dead on network-start

### ISSUE THREAD

**Issue by claudiumilea** [vegaprotocol/vega#7534] opened 2023-02-08 09:39 UTC
# Problem encountered
Wallet is dead on network startup

# Observed behaviour
when starting the network with `make start-network` wallet is dead at the end of the network start process

# Expected behaviour
wallet should be started

# System response
Describe what the system response was, include the output from the command, automation, or else.

# Steps to reproduce

## Manual
Steps to reproduce the behaviour manually:
1. make stop-network
2. make cleanup
3. pkill -9 nomad
4. restart docker desktop
5. make start nomad - and it starts successfully
6. make start-network - and network starts but wallet is dead
7. (see network start log below)

# Evidence

## Logs
#wallet log
stderr: {"error":"could not start the service as an application is already served on \"http://http://127.0.0.1:1789\""}
stdout: CLI logs located at: /Users/claudiumilea/repo/networkdata/testnet/wallet/state/wallet-cli/logs/2023-02-08-09-25-05-43439.log
! Long-living tokens enabled
✓ Service logs located at: /Users/claudiumilea/repo/networkdata/testnet/wallet/state/wallet-service/logs/2023-02-08-09-25-05-43439.log

{"level":"warn","@timestamp":"2023-02-08T11:25:05.982+0200","logger":"command","caller":"commands/service_run.go:193","message":"Current software is a released version","version":"v0.68.0-dev"}
{"level":"warn","@timestamp":"2023-02-08T11:25:05.982+0200","logger":"command","caller":"commands/service_run.go:222","message":"Long-living tokens enabled"}
{"level":"info","@timestamp":"2023-02-08T11:25:05.983+0200","logger":"command","caller":"commands/service_run.go:335","message":"No TTY detected"}
{"level":"info","@timestamp":"2023-02-08T11:25:05.983+0200","logger":"command","caller":"commands/service_run.go:342","message":"Automatic consent enabled."}
{"level":"error","@timestamp":"2023-02-08T11:25:06.017+0200","logger":"command","caller":"commands/service_run.go:284","message":"Failed to start HTTP server","error":"could not start the service as an application is already served on \"http://http://127.0.0.1:1789\""}

{"level":"info","@timestamp":"2023-02-08T11:25:05.983+0200","logger":"service","caller":"service/starter.go:302","message":"The network configuration has been loaded","network":"DV","network":"DV"}
{"level":"warn","@timestamp":"2023-02-08T11:25:05.983+0200","logger":"service","caller":"service/starter.go:106","message":"The compatibility check between the software and the network has been skipped","network":"DV"}
{"level":"info","@timestamp":"2023-02-08T11:25:05.983+0200","logger":"service","caller":"service/starter.go:319","message":"The service has already been initialised","network":"DV"}
{"level":"error","@timestamp":"2023-02-08T11:25:06.017+0200","logger":"service","caller":"service/starter.go:366","message":"Could not start the service as an application is already served on that url","network":"DV","url":"http://http://127.0.0.1:1789"}

#network start log
2023/02/08 11:24:33 Updating genesis with: /Users/claudiumilea/repo/networkdata/vega [genesis --home /Users/claudiumilea/repo/networkdata/testnet/vega/node1 --passphrase-file /Users/claudiumilea/repo/networkdata/testnet/vega/node1/node-vega-wallet-pass.txt update --tm-home /Users/claudiumilea/repo/networkdata/testnet/tendermint/node1 --dry-run]
2023/02/08 11:24:35 Updating genesis with: /Users/claudiumilea/repo/networkdata/vega [genesis --home /Users/claudiumilea/repo/networkdata/testnet/vega/node3 --passphrase-file /Users/claudiumilea/repo/networkdata/testnet/vega/node3/node-vega-wallet-pass.txt update --tm-home /Users/claudiumilea/repo/networkdata/testnet/tendermint/node3 --dry-run]
2023/02/08 11:24:35 Updating genesis with: /Users/claudiumilea/repo/networkdata/vega [genesis --home /Users/claudiumilea/repo/networkdata/testnet/vega/node4 --passphrase-file /Users/claudiumilea/repo/networkdata/testnet/vega/node4/node-vega-wallet-pass.txt update --tm-home /Users/claudiumilea/repo/networkdata/testnet/tendermint/node4 --dry-run]
2023/02/08 11:24:35 Initiating wallet "wallet-1" with: [wallet init --output json --home /Users/claudiumilea/repo/networkdata/testnet/wallet]
2023/02/08 11:24:37 Initiating api-token wallet "wallet-1" with: [wallet api-token init --home /Users/claudiumilea/repo/networkdata/testnet/wallet --passphrase-file /Users/claudiumilea/repo/networkdata/api-token-passphrase-file]
2023/02/08 11:24:37 Importing network to wallet "wallet-1" with: [wallet network import --output json --home /Users/claudiumilea/repo/networkdata/testnet/wallet --from-file /Users/claudiumilea/repo/networkdata/testnet/wallet/config.toml]
2023/02/08 11:24:37 generating network success
Generate network: End
Start network: Start
2023/02/08 11:24:37 starting network
2023/02/08 11:24:41 Update for job: "toxiproxy", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:24:45 Update for job: "toxiproxy", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:24:49 Update for job: "toxiproxy", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2023/02/08 11:24:53 Update for job: "postgres-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:24:53 Update for job: "ganache-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:24:57 Update for job: "ganache-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:24:57 Update for job: "postgres-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:01 Update for job: "ganache-1", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2023/02/08 11:25:01 Update for job: "postgres-1", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:05 Update for job: "postgres-1", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2023/02/08 11:25:05 adding node set "testnet-nodeset-validators-0-validator" with default Nomad job definition
2023/02/08 11:25:05 adding node set "testnet-nodeset-validators-1-validator" with default Nomad job definition
2023/02/08 11:25:05 adding node set "testnet-nodeset-validators-2-validator" with default Nomad job definition
2023/02/08 11:25:05 adding node set "testnet-nodeset-validators-clef-3-validator" with default Nomad job definition
2023/02/08 11:25:05 adding node set "testnet-nodeset-validators-clef-4-validator" with default Nomad job definition
2023/02/08 11:25:05 adding node set "testnet-nodeset-full-5-full" with default Nomad job definition
2023/02/08 11:25:07 Probing Postgres with id "testnet-nodeset-full-5-full" connection "user=vega dbname=vega5 password=vega port=5532 sslmode=disable" with query "select 10 + 10"
2023/02/08 11:25:07 Probing Postgres with id "testnet-nodeset-full-5-full" was successful, result: 20
2023/02/08 11:25:09 Update for job: "testnet-nodeset-validators-clef-3-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:09 Update for job: "testnet-nodeset-validators-2-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:09 Update for job: "testnet-nodeset-validators-0-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:09 Update for job: "testnet-nodeset-validators-1-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:09 Update for job: "testnet-nodeset-validators-clef-4-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:09 Update for job: "testnet-vegawallet", jobStatus: dead, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:09 Update for job: "testnet-faucet", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:11 Update for job: "testnet-nodeset-full-5-full", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:13 Update for job: "testnet-nodeset-validators-0-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:13 Update for job: "testnet-nodeset-validators-clef-3-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:13 Update for job: "testnet-nodeset-validators-2-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:13 Update for job: "testnet-nodeset-validators-1-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:13 Update for job: "testnet-nodeset-validators-clef-4-validator", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:13 Update for job: "testnet-vegawallet", jobStatus: dead, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:13 Update for job: "testnet-faucet", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:15 Update for job: "testnet-nodeset-full-5-full", jobStatus: running, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:17 Update for job: "testnet-nodeset-validators-2-validator", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2023/02/08 11:25:17 Update for job: "testnet-nodeset-validators-0-validator", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2023/02/08 11:25:17 Update for job: "testnet-nodeset-validators-clef-3-validator", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2023/02/08 11:25:17 Update for job: "testnet-nodeset-validators-clef-4-validator", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2023/02/08 11:25:17 Update for job: "testnet-nodeset-validators-1-validator", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2023/02/08 11:25:17 Update for job: "testnet-vegawallet", jobStatus: dead, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:17 Update for job: "testnet-faucet", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2023/02/08 11:25:19 Update for job: "testnet-nodeset-full-5-full", jobStatus: running, deploymentStatus: "successful", another: Deployment completed successfully
2023/02/08 11:25:21 Update for job: "testnet-vegawallet", jobStatus: dead, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:25 Update for job: "testnet-vegawallet", jobStatus: dead, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:29 Update for job: "testnet-vegawallet", jobStatus: dead, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:33 Update for job: "testnet-vegawallet", jobStatus: dead, deploymentStatus: "running", another: Deployment is running
2023/02/08 11:25:37 Job "testnet-vegawallet" has timed out output: Task: "wallet-1", State: "dead", Events: "Received: Task received by client -> Task Setup: Building Task Directory -> Started: Task started by client -> Terminated: Exit Code: 1 -> Not Restarting: Policy allows no restarts -> Killing: Sent interrupt. Waiting 20s before force killing"
2023/02/08 11:25:37 Job "testnet-vegawallet" has timed out output: Task: "capsule-logscolletor", State: "dead", Events: "Received: Task received by client -> Task Setup: Building Task Directory -> Started: Task started by client -> Sibling Task Failed: Task's sibling \"wallet-1\" failed -> Killing: Sent interrupt. Waiting 20s before force killing -> Terminated: Exit Code: 1 -> Killed: Task successfully killed"

Logs from failed testnet-vegawallet job:
-------- wallet-1.stderr-2023-02-08T11:25:05+02:00.log:
{"error":"could not start the service as an application is already served on \"http://http://127.0.0.1:1789\""}

-------- wallet-1.stdout-2023-02-08T11:25:05+02:00.log:
✓ CLI logs located at: /Users/claudiumilea/repo/networkdata/testnet/wallet/state/wallet-cli/logs/2023-02-08-09-25-05-43439.log
! Long-living tokens enabled
✓ Service logs located at: /Users/claudiumilea/repo/networkdata/testnet/wallet/state/wallet-service/logs/2023-02-08-09-25-05-43439.log

2023/02/08 11:25:37 Part of the network could not start, but it has been required to not stop existing jobs on failure, so we continue as normal...
2023/02/08 11:25:37 Network successfully started.
2023/02/08 11:25:37 printing exposed network addresses
Job "clef-3"
  - localhost:8553
Job "clef-4"
  - localhost:8554
Job "ganache-1"
  - localhost:8545
Job "postgres-1"
  - localhost:5532
Job "testnet-faucet" - "faucet"
  - localhost:1790
Job "testnet-nodeset-full-5-full" - "data-node"
  - Gateway.GraphQL: localhost:3058
  - Pprof: localhost:6560
  - Broker.SocketConfig: localhost:33055
  - API: localhost:3057
  - Gateway.REST: localhost:3059
Job "testnet-nodeset-full-5-full" - "vega"
  - API: localhost:3052
  - API.REST: localhost:3053
Job "testnet-nodeset-validators-0-validator" - "vega"
  - API: localhost:3002
  - API.REST: localhost:3003
Job "testnet-nodeset-validators-1-validator" - "vega"
  - API.REST: localhost:3013
  - API: localhost:3012
Job "testnet-nodeset-validators-2-validator" - "vega"
  - API.REST: localhost:3023
  - API: localhost:3022
Job "testnet-nodeset-validators-clef-3-validator" - "vega"
  - API.REST: localhost:3033
  - API: localhost:3032
Job "testnet-nodeset-validators-clef-4-validator" - "vega"
  - API: localhost:3042
  - API.REST: localhost:3043
Start network: End
Setup network multisig: Start
2023/02/08 11:25:38 Current multisig threshold: 500
2023/02/08 11:25:38 Computed signature for set_threshold to 1: 0xe9f852328a9b345acb1708470d623c352ed137b36eb91f48091b534b84f29e016cd978382228bbc4edf6f0bffaada65030782e0225a885f0fde1d27a93c2f94001
2023/02/08 11:25:39 Updated multisig threshold: 1
2023/02/08 11:25:39 Number of signers for multisig: 1
2023/02/08 11:25:40 Computed signature for add_signer for 0xF634d1aC8060D53dC1Ed112dC525cc87783f22ba: 0x9758857a84734bb535ecd039dcb95da353effa61a1b6a82aea911c5bffd0aebf7cdf58d02abce3c4d64c9c677e9e3418e1265dccbdcdcab49e8277654356419800
2023/02/08 11:25:41 Added 0xF634d1aC8060D53dC1Ed112dC525cc87783f22ba as a multisig validator
2023/02/08 11:25:41 Computed signature for add_signer for 0xA8f3Cb5Ea15F5a0624E9084F526eaB92C2B37487: 0xec6c14997c1dfaa9c79d5bb170df5aa4e0426cfdfe978f2713a1c7d0a6677b3165de6104c899b1647e5e127609a9fc95ab95edd994d028995757c4e059a67ecb01
2023/02/08 11:25:42 Added 0xA8f3Cb5Ea15F5a0624E9084F526eaB92C2B37487 as a multisig validator
2023/02/08 11:25:42 Computed signature for add_signer for 0x843bf6fcf6550382a87bf01e12228682900571e0: 0xd4a360866645e4e0e8ec0a470cf52be499753452cb925ef93db9d1bed5563f63032214f43ced4ff3a04c388a9d74aaf253bf638cccc76e887d5a30d0158b795c01
2023/02/08 11:25:43 Added 0x843bf6fcf6550382a87bf01e12228682900571e0 as a multisig validator
2023/02/08 11:25:43 Computed signature for add_signer for 0xc5bf831ddf098fe218958d74676c6ffc64baa970: 0x6055cc2418cb3492b9886e5e744f779772f7dff4a5780d0467bfe42338e289d813f853753340942be0ecefa869d3c1b8b8037cfe52bad186cdcbde1b02494a6d00
2023/02/08 11:25:44 Added 0xc5bf831ddf098fe218958d74676c6ffc64baa970 as a multisig validator
2023/02/08 11:25:44 Computed signature for add_signer for 0x72Ff9Bc0D0978276AE8497dd635cdBDB6F992172: 0x627305bb799de4c13806643c5d50c9bd3b91c5020f93811b99727dffb39be10b4581473bba27774a9afdecc10017fdae43b3c4e7efed0c5e9176b2488a07e65001
2023/02/08 11:25:45 Added 0x72Ff9Bc0D0978276AE8497dd635cdBDB6F992172 as a multisig validator
2023/02/08 11:25:45 Updated number of signers for multisig: 6
2023/02/08 11:25:45 Computed signature for remove_signer for 0xEe7D375bcB50C26d52E1A4a472D8822A2A22d94F: 0xbf6c9c985228979bcd1799aa0179cf6fde4a6d1ceddc6a69183863ccb651d1721a5de92433ce04d068bfdd85e3dfe7318f61708998f8b4a9d944f747d3e0abe500
2023/02/08 11:25:46 Removed the 0xEe7D375bcB50C26d52E1A4a472D8822A2A22d94F signer from multisig control
2023/02/08 11:25:46 Updated number of signers for multisig: 5
2023/02/08 11:25:46 Current multisig threshold: 1
2023/02/08 11:25:47 Computed signature for set_threshold to 667: 0xca38d3d96255712dbb10d2c90aab236da546abae8fb14dbc41d8fb4fc21483b82c1face6e174e6b28a9317d3293878f6cb84beba2bb4422123440843571f64650144741b8ec496b4b2f107f5cb6b6fdd5930d4e2050b36fbecc8ec3daa72ed5e555422e802d6aa94f97138ca3a435d8be883e35586dce528f3d03a224a340695890059a2a1291ad5a3fea2885aae9166023d059530ed0c252f0e36e787bb836bf4270d88d99f582afa2c5c9f22e169ae96fb572754dca7731565acb1f3006849ee231c3e3a5466fd6afb8d1fb12a3d546a5f020e3785319e8547c41049bed79c29d92e754b458893b58f0337c68819b2b0cf7082763f4e8d73a6c4f2fc2bdec907c7021b50e796e24fc1d1099be1edc66fe9a63d450744e1c41eb186cd7e7da156b7f03b1e51b81839bf69546de64318d5aaec7ac1134d31404396325f85a11bb857f91600
2023/02/08 11:25:48 Updated multisig threshold: 667

## Additional context
Add any other context about the problem here including; system version numbers, components affected.

# Definition of Done
>ℹ️ Not every issue will need every item checked, however, every item on this list should be properly considered and actioned to meet the [DoD](https://github.com/vegaprotocol/vega/blob/develop/DEFINITION_OF_DONE.md).

**Before Merging**
- [ ] Code refactored to meet SOLID and other code design principles
- [ ] Code is compilation error, warning, and hint free
- [ ] Carry out a basic happy path end-to-end check of the new code
- [ ] All APIs are documented so auto-generated documentation is created
- [ ] All bug recreation steps can be followed without presenting the original error/bug
- [ ] All Unit, Integration and BVT tests are passing
- [ ] Implementation is peer reviewed (coding standards, meeting acceptance criteria, code/design quality)
- [ ] Create [front end](https://github.com/vegaprotocol/token-frontend/issues) or [console](https://github.com/vegaprotocol/console/issues) tickets with feature labels (should be done when starting the work if dependencies known i.e. API changes)

**After Merging**
- [ ] Move development ticket to `Done` if there is **NO** requirement for new [system-tests](https://github.com/vegaprotocol/system-tests/issues)
- [ ] Resolve any issues with broken system-tests
- [ ] Create [documentation](https://github.com/vegaprotocol/documentation/issues) tickets with feature labels if functionality has changed, or is a new feature

**Comment by gordsport** [comment] 2023-02-13 11:31
@claudiumilea 
It seems that this issue is only being presented on your machine and this cant be re-produced elsewhere.

Unless you can add further information we may need to close as 'cant reproduce'

**Comment by gordsport** [comment] 2023-03-20 11:06
Closing to be re-opened with more information pending a test to reproduce

**Closed by gordsport** 2023-03-20 11:06 UTC
Labels: bug
